import type {
  AnatomyEdge,
  AnatomyLane,
  AnatomyNode,
  AnatomyRisk,
  GameEngineAnatomySpec,
  GameEngineChapter,
} from "./game-engine-anatomy-types";

const LANES: AnatomyLane[] = [
  { id: "tools", label: "工具 / 资产", y: 72 },
  { id: "runtime", label: "运行时核心", y: 214 },
  { id: "platform", label: "平台 / 输出", y: 356 },
];

const xs = [110, 250, 390, 530, 670, 810] as const;

function makeSpec({
  title,
  subtitle,
  nodes,
  edges,
  risks,
  steps,
}: {
  title: string;
  subtitle: string;
  nodes: AnatomyNode[];
  edges?: AnatomyEdge[];
  risks: AnatomyRisk[];
  steps: GameEngineAnatomySpec["steps"];
}): GameEngineAnatomySpec {
  return {
    title,
    subtitle,
    lanes: LANES,
    nodes,
    edges:
      edges ??
      nodes.slice(0, -1).map((node, i) => ({
        from: node.id,
        to: nodes[i + 1].id,
        step: Math.min(3, Math.floor(i / 2) + 1) as 1 | 2 | 3,
      })),
    risks,
    steps,
  };
}

export const GAME_ENGINE_ANATOMY: Record<
  GameEngineChapter,
  GameEngineAnatomySpec
> = {
  intro: makeSpec({
    title: "游戏产品生产机器",
    subtitle:
      "编辑器、资产管线、运行时和平台一起交付玩家体验；渲染器只是其中一块。",
    nodes: [
      {
        id: "editor",
        label: "编辑器",
        note: "关卡与工具入口",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "assets",
        label: "资产管线",
        note: "内容变成运行时数据",
        lane: "tools",
        x: xs[1],
        tone: "data",
        step: 1,
      },
      {
        id: "core",
        label: "运行时核心",
        note: "调度所有子系统",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "systems",
        label: "渲染 / 音频 / 输入",
        note: "专门系统协作",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "platform",
        label: "平台抽象",
        note: "主机、PC、移动端差异",
        lane: "platform",
        x: xs[4],
        step: 3,
      },
      {
        id: "player",
        label: "玩家反馈",
        note: "画面、声音、操作响应",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "把引擎误当渲染器", x: 424, y: 94, tone: "risk", step: 2 },
      { label: "平台差异回灌到业务层", x: 690, y: 214, tone: "wait", step: 3 },
    ],
    steps: [
      {
        title: "内容与工具进入生产线",
        focus: "先看编辑器和资产管线如何把团队产物变成可运行数据。",
      },
      {
        title: "运行时协调多个专门系统",
        focus: "核心不是画图，而是在同一帧预算里调度渲染、音频、输入和玩法。",
      },
      {
        title: "平台输出形成玩家反馈",
        focus: "最终结果落到平台 API、硬件和玩家感知，架构边界在这里被验证。",
      },
    ],
  }),
  tools: makeSpec({
    title: "代码与资产到可运行包",
    subtitle: "工具链的质量决定团队每天改动能否快速、可复现地抵达目标平台。",
    nodes: [
      {
        id: "ide",
        label: "IDE / 编辑器",
        note: "代码与内容创作",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "vcs",
        label: "提交 / CI",
        note: "版本与自动检查",
        lane: "tools",
        x: xs[1],
        step: 1,
      },
      {
        id: "compile",
        label: "编译链接",
        note: "源码变二进制",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "import",
        label: "资产导入",
        note: "贴图模型转格式",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "package",
        label: "构建部署",
        note: "包体与符号产物",
        lane: "platform",
        x: xs[4],
        tone: "output",
        step: 3,
      },
      {
        id: "debug",
        label: "调试回环",
        note: "日志、断点、Profile",
        lane: "platform",
        x: xs[5],
        tone: "risk",
        step: 3,
      },
    ],
    risks: [
      { label: "本地能跑 CI 不过", x: 286, y: 95, tone: "risk", step: 1 },
      { label: "导入设置不可复现", x: 504, y: 196, tone: "wait", step: 2 },
    ],
    steps: [
      {
        title: "创作物先进入版本化入口",
        focus: "IDE、编辑器和提交系统决定改动是否可追踪。",
      },
      {
        title: "代码与资产分别被转换",
        focus: "编译和资产导入是两条生产线，任何一条慢都会拖慢迭代。",
      },
      {
        title: "部署后用工具回收证据",
        focus: "调试回环把运行结果带回开发机，工具链才闭合。",
      },
    ],
  }),
  software: makeSpec({
    title: "模块边界解剖",
    subtitle:
      "架构的第一责任是控制复杂度：依赖方向、所有权、错误和测试边界都要画清楚。",
    nodes: [
      {
        id: "feature",
        label: "功能需求",
        note: "玩法或引擎能力",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "interface",
        label: "接口契约",
        note: "输入、输出、错误",
        lane: "runtime",
        x: xs[1],
        tone: "data",
        step: 1,
      },
      {
        id: "module",
        label: "模块实现",
        note: "隐藏内部复杂度",
        lane: "runtime",
        x: xs[2],
        step: 2,
      },
      {
        id: "owner",
        label: "数据所有权",
        note: "生命周期与写入者",
        lane: "runtime",
        x: xs[3],
        tone: "wait",
        step: 2,
      },
      {
        id: "error",
        label: "错误传播",
        note: "失败谁知道",
        lane: "platform",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "tests",
        label: "测试缝隙",
        note: "边界可替换可验证",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "循环依赖", x: 338, y: 106, tone: "risk", step: 2 },
      { label: "错误只剩日志没人处理", x: 640, y: 222, tone: "risk", step: 3 },
    ],
    steps: [
      {
        title: "先把需求变成接口契约",
        focus: "不要先画类图，先画输入、输出和失败形态。",
      },
      {
        title: "实现内部守住所有权",
        focus: "模块内部可以复杂，但数据生命周期和写入者必须单一清晰。",
      },
      {
        title: "错误与测试从边界穿出",
        focus: "好边界应该能暴露失败，也能被替身测试。",
      },
    ],
  }),
  parallel: makeSpec({
    title: "帧内任务图",
    subtitle: "并行的难点不是开线程，而是工作拆分、数据边界和同步栅栏。",
    nodes: [
      {
        id: "main",
        label: "主线程",
        note: "采样输入与帧主控",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "graph",
        label: "任务图",
        note: "拆分依赖关系",
        lane: "tools",
        x: xs[1],
        step: 1,
      },
      {
        id: "queue",
        label: "任务队列",
        note: "可执行工作包",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "workers",
        label: "Worker 池",
        note: "并行消费任务",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "barrier",
        label: "同步栅栏",
        note: "等关键结果齐",
        lane: "platform",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "frame",
        label: "帧结束合并",
        note: "写回可见状态",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "假共享 / 锁竞争", x: 500, y: 112, tone: "wait", step: 2 },
      { label: "栅栏等待吃掉并行收益", x: 670, y: 214, tone: "risk", step: 3 },
    ],
    steps: [
      {
        title: "主线程声明本帧工作",
        focus: "先确定主线程保留什么，哪些工作能变成任务图。",
      },
      {
        title: "Worker 消费独立任务",
        focus: "并行收益来自数据边界清楚、依赖少、任务粒度合适。",
      },
      {
        title: "同步点决定真实成本",
        focus: "帧尾合并和栅栏等待才是并发架构的考试。",
      },
    ],
  }),
  math: makeSpec({
    title: "空间协议",
    subtitle: "数学是引擎模块之间交换空间、方向和运动的协议。",
    nodes: [
      {
        id: "local",
        label: "局部空间",
        note: "模型自身坐标",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "world",
        label: "世界空间",
        note: "对象摆到场景",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "view",
        label: "视图空间",
        note: "相机观察系",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "clip",
        label: "裁剪空间",
        note: "投影和齐次坐标",
        lane: "platform",
        x: xs[3],
        step: 2,
      },
      {
        id: "motion",
        label: "方向 / 曲线",
        note: "四元数与插值",
        lane: "tools",
        x: xs[4],
        tone: "data",
        step: 3,
      },
      {
        id: "debug",
        label: "调试线框",
        note: "把空间错误画出来",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "矩阵顺序反了", x: 280, y: 212, tone: "risk", step: 1 },
      { label: "左手 / 右手系混用", x: 468, y: 214, tone: "risk", step: 2 },
    ],
    steps: [
      {
        title: "对象先从局部进入世界",
        focus: "看清每个 transform 把数据从哪个空间带到哪个空间。",
      },
      {
        title: "相机和投影改变解释方式",
        focus: "渲染、剔除和拾取都依赖相同的空间约定。",
      },
      {
        title: "用调试可视化暴露数学错误",
        focus: "坐标轴、包围盒、曲线和线框能把抽象错误变成画面证据。",
      },
    ],
  }),
  support: makeSpec({
    title: "底层服务底座",
    subtitle:
      "支撑系统不显眼，但日志、内存、时间和配置坏掉会拖垮所有上层模块。",
    nodes: [
      {
        id: "config",
        label: "配置 / 启动",
        note: "决定系统初始形态",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "memory",
        label: "内存分配",
        note: "对象与缓存来源",
        lane: "runtime",
        x: xs[1],
        tone: "wait",
        step: 1,
      },
      {
        id: "containers",
        label: "容器 / 字符串",
        note: "基础数据结构",
        lane: "runtime",
        x: xs[2],
        step: 2,
      },
      {
        id: "time",
        label: "时间系统",
        note: "帧时间与定时器",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "log",
        label: "日志 / 断言",
        note: "失败观测入口",
        lane: "platform",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "systems",
        label: "上层模块",
        note: "渲染、玩法、音频共用",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "分配峰值造成卡顿", x: 250, y: 112, tone: "wait", step: 1 },
      { label: "没有上下文的日志", x: 620, y: 212, tone: "risk", step: 3 },
    ],
    steps: [
      {
        title: "启动时铺好基础服务",
        focus: "配置和内存系统决定后续模块能不能稳定创建对象。",
      },
      {
        title: "运行中所有模块共享底座",
        focus: "容器、时间和字符串不是小事，它们在每帧被高频使用。",
      },
      {
        title: "故障通过日志和断言浮出",
        focus: "支撑系统要给上层提供足够的失败证据。",
      },
    ],
  }),
  resources: makeSpec({
    title: "资产生命周期",
    subtitle: "资源系统把慢 IO、离线格式和运行时缓存组织成可预测的数据供应。",
    nodes: [
      {
        id: "source",
        label: "源资产",
        note: "FBX、PNG、WAV",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "importer",
        label: "导入器",
        note: "校验与元数据",
        lane: "tools",
        x: xs[1],
        step: 1,
      },
      {
        id: "cook",
        label: "Cook",
        note: "平台专用格式",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "bundle",
        label: "包体 / 文件系统",
        note: "布局与寻址",
        lane: "platform",
        x: xs[3],
        step: 2,
      },
      {
        id: "async",
        label: "异步加载",
        note: "IO 到内存",
        lane: "runtime",
        x: xs[4],
        tone: "wait",
        step: 3,
      },
      {
        id: "cache",
        label: "运行时缓存",
        note: "句柄与生命周期",
        lane: "runtime",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "Cook 结果与源资产脱节", x: 392, y: 114, tone: "risk", step: 2 },
      { label: "主线程等待 IO", x: 672, y: 214, tone: "wait", step: 3 },
    ],
    steps: [
      {
        title: "源资产先被导入和校验",
        focus: "导入阶段决定资源是否有稳定 ID、元数据和错误报告。",
      },
      {
        title: "Cook 与包体把资源变成平台产物",
        focus: "运行时不该理解所有创作格式，只消费平台友好的数据。",
      },
      {
        title: "异步加载与缓存服务一帧",
        focus: "资源最终要以句柄和缓存形式供渲染、音频、玩法使用。",
      },
    ],
  }),
  loop: makeSpec({
    title: "一帧时间轴",
    subtitle: "主循环是引擎心跳，固定步模拟、变步渲染和提交边界共同决定手感。",
    nodes: [
      {
        id: "input",
        label: "输入采样",
        note: "收集本帧意图",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "fixed",
        label: "固定步模拟",
        note: "物理与确定性状态",
        lane: "runtime",
        x: xs[1],
        tone: "wait",
        step: 1,
      },
      {
        id: "game",
        label: "玩法更新",
        note: "脚本与状态机",
        lane: "runtime",
        x: xs[2],
        step: 2,
      },
      {
        id: "anim",
        label: "动画 / 物理回写",
        note: "生成可渲染姿态",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "render",
        label: "渲染提交",
        note: "构建 GPU 命令",
        lane: "platform",
        x: xs[4],
        tone: "wait",
        step: 3,
      },
      {
        id: "present",
        label: "Present",
        note: "显示到屏幕",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "spiral of death", x: 250, y: 214, tone: "risk", step: 1 },
      { label: "CPU/GPU 队列互等", x: 670, y: 214, tone: "wait", step: 3 },
    ],
    steps: [
      {
        title: "帧开头采样并推进固定步",
        focus: "输入和固定步模拟定义本帧状态基础。",
      },
      {
        title: "玩法、动画、物理生成可见状态",
        focus: "中段系统把状态推进到可以提交渲染的形态。",
      },
      {
        title: "提交给 GPU 并等待显示",
        focus: "帧尾要看 CPU/GPU 边界、vsync 和 Present 成本。",
      },
    ],
  }),
  hid: makeSpec({
    title: "硬件输入到玩家意图",
    subtitle: "输入系统把设备差异藏起来，把玩家想做的动作暴露给玩法。",
    nodes: [
      {
        id: "device",
        label: "设备事件",
        note: "键鼠、手柄、触屏",
        lane: "platform",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "sample",
        label: "采样 / 去抖",
        note: "时间戳与原始值",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "normalize",
        label: "归一化",
        note: "轴、死区、布局",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "map",
        label: "动作映射",
        note: "Jump、Aim、Menu",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "gameplay",
        label: "玩法动作",
        note: "状态改变与命令",
        lane: "runtime",
        x: xs[4],
        tone: "output",
        step: 3,
      },
      {
        id: "feedback",
        label: "反馈",
        note: "震动、UI、音效",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "死区与平台布局差异", x: 390, y: 214, tone: "risk", step: 2 },
      { label: "输入延迟难定位", x: 668, y: 214, tone: "wait", step: 3 },
    ],
    steps: [
      {
        title: "先保留设备事件的时间证据",
        focus: "输入 bug 常常是时间问题，原始采样不能太早丢。",
      },
      {
        title: "归一化后映射到动作",
        focus: "玩法不应该直接关心某个手柄轴或键盘布局。",
      },
      {
        title: "动作影响玩法并产生反馈",
        focus: "输入链路闭合在画面、音效、震动和 UI 响应。",
      },
    ],
  }),
  debug: makeSpec({
    title: "可观测性闭环",
    subtitle: "调试工具让隐藏状态变成证据：抓取、解释、回放，再把修复自动化。",
    nodes: [
      {
        id: "capture",
        label: "捕获现场",
        note: "日志、dump、trace",
        lane: "platform",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "breakpoint",
        label: "断点 / 检查器",
        note: "局部状态",
        lane: "tools",
        x: xs[1],
        step: 1,
      },
      {
        id: "profiler",
        label: "Profiler",
        note: "CPU/GPU/内存时间线",
        lane: "tools",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "visual",
        label: "可视化调试",
        note: "碰撞、骨骼、资源",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "replay",
        label: "回放",
        note: "复现输入和状态",
        lane: "runtime",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "automation",
        label: "自动化验证",
        note: "防止问题回归",
        lane: "tools",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      {
        label: "只能看到现象看不到状态",
        x: 246,
        y: 112,
        tone: "risk",
        step: 1,
      },
      { label: "无法复现就无法修", x: 610, y: 214, tone: "wait", step: 3 },
    ],
    steps: [
      {
        title: "先捕获现场和局部状态",
        focus: "断点和日志解决的是此刻发生了什么。",
      },
      {
        title: "用 Profile 和可视化解释系统状态",
        focus: "复杂问题需要时间线、空间线和资源状态一起看。",
      },
      {
        title: "回放后固化为自动化验证",
        focus: "修复不是终点，能复现并防回归才闭环。",
      },
    ],
  }),
  rendering: makeSpec({
    title: "CPU 到 GPU 渲染管线",
    subtitle: "现代渲染引擎的关键是数据流、可见性和 GPU 工作编排。",
    nodes: [
      {
        id: "scene",
        label: "场景图",
        note: "对象、灯光、相机",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "visibility",
        label: "可见性",
        note: "剔除和排序",
        lane: "runtime",
        x: xs[1],
        tone: "wait",
        step: 1,
      },
      {
        id: "material",
        label: "材质 / Mesh",
        note: "渲染资源绑定",
        lane: "tools",
        x: xs[2],
        step: 2,
      },
      {
        id: "graph",
        label: "Render Graph",
        note: "Pass 与资源依赖",
        lane: "runtime",
        x: xs[3],
        tone: "wait",
        step: 2,
      },
      {
        id: "cmd",
        label: "Command Buffer",
        note: "GPU 命令",
        lane: "platform",
        x: xs[4],
        step: 3,
      },
      {
        id: "gpu",
        label: "GPU / Framebuffer",
        note: "像素落地",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "过度提交不可见物体", x: 250, y: 214, tone: "wait", step: 1 },
      { label: "资源状态转换错误", x: 530, y: 214, tone: "risk", step: 2 },
    ],
    steps: [
      {
        title: "场景先被筛成可见集合",
        focus: "可见性决定后面有多少 draw 和 pass 需要处理。",
      },
      {
        title: "材质与 Render Graph 组织 GPU 工作",
        focus: "现代渲染更像依赖图编排，不是简单顺序画物体。",
      },
      {
        title: "命令提交后才进入硬件边界",
        focus: "最终瓶颈可能在 CPU 提交，也可能在 GPU 执行。",
      },
    ],
  }),
  animation: makeSpec({
    title: "动画姿态生成链",
    subtitle: "动画系统把离线 clip、状态机和混合结果变成本帧骨骼姿态。",
    nodes: [
      {
        id: "clips",
        label: "Clip 资源",
        note: "关键帧和曲线",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "state",
        label: "状态机",
        note: "Idle、Run、Jump",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "blend",
        label: "Blend Tree",
        note: "按参数混合",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "skeleton",
        label: "骨骼采样",
        note: "local pose",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "pose",
        label: "Pose 输出",
        note: "蒙皮和事件",
        lane: "platform",
        x: xs[4],
        tone: "output",
        step: 3,
      },
      {
        id: "root",
        label: "Root Motion",
        note: "回写角色位移",
        lane: "runtime",
        x: xs[5],
        tone: "risk",
        step: 3,
      },
    ],
    risks: [
      { label: "状态迁移抖动", x: 250, y: 214, tone: "risk", step: 1 },
      {
        label: "根运动与物理抢写 Transform",
        x: 722,
        y: 112,
        tone: "risk",
        step: 3,
      },
    ],
    steps: [
      {
        title: "资源和状态机决定播放意图",
        focus: "先看当前状态为什么选择某些 clip。",
      },
      {
        title: "混合与采样生成骨骼姿态",
        focus: "Blend、mask 和采样成本决定动画中段质量。",
      },
      {
        title: "姿态输出并回写运动",
        focus: "最终结果要供渲染蒙皮，也可能改变角色位移。",
      },
    ],
  }),
  physics: makeSpec({
    title: "物理求解流水线",
    subtitle: "碰撞和刚体系统用阶段化管线把形状重叠变成稳定的 Transform 回写。",
    nodes: [
      {
        id: "shape",
        label: "Shape / Body",
        note: "碰撞形状和质量",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "broad",
        label: "Broadphase",
        note: "快速找候选对",
        lane: "runtime",
        x: xs[1],
        tone: "wait",
        step: 1,
      },
      {
        id: "narrow",
        label: "Narrowphase",
        note: "精确接触点",
        lane: "runtime",
        x: xs[2],
        step: 2,
      },
      {
        id: "solver",
        label: "Constraint Solver",
        note: "冲量与约束",
        lane: "runtime",
        x: xs[3],
        tone: "wait",
        step: 2,
      },
      {
        id: "events",
        label: "碰撞事件",
        note: "Enter、Stay、Exit",
        lane: "platform",
        x: xs[4],
        tone: "output",
        step: 3,
      },
      {
        id: "transform",
        label: "Transform 回写",
        note: "同步到场景",
        lane: "runtime",
        x: xs[5],
        tone: "risk",
        step: 3,
      },
    ],
    risks: [
      { label: "候选对爆炸", x: 250, y: 214, tone: "wait", step: 1 },
      { label: "脚本与物理双写位置", x: 718, y: 214, tone: "risk", step: 3 },
    ],
    steps: [
      {
        title: "形状先进入粗略筛选",
        focus: "Broadphase 的任务是少做精确碰撞。",
      },
      {
        title: "接触点被求解成运动结果",
        focus: "Narrowphase 和 Solver 是精度、稳定性和性能的核心。",
      },
      {
        title: "事件与 Transform 回到游戏世界",
        focus: "物理结果要被玩法消费，也要同步给渲染。",
      },
    ],
  }),
  audio: makeSpec({
    title: "声音从资源到扬声器",
    subtitle: "音频系统把音频资源、空间信息和混音图组织成低延迟输出。",
    nodes: [
      {
        id: "asset",
        label: "音频资源",
        note: "WAV、压缩流",
        lane: "tools",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "source",
        label: "声源",
        note: "位置、音量、触发",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "spatial",
        label: "空间化",
        note: "距离、方向、遮挡",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "mix",
        label: "混音总线",
        note: "分组、ducking、效果",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "dsp",
        label: "DSP Buffer",
        note: "低延迟音频线程",
        lane: "platform",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "output",
        label: "输出设备",
        note: "扬声器 / 耳机",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "流式资源抢 IO", x: 250, y: 112, tone: "wait", step: 1 },
      { label: "buffer underrun 爆音", x: 672, y: 214, tone: "risk", step: 3 },
    ],
    steps: [
      {
        title: "声音先从资源和声源进入场景",
        focus: "音频资源只是素材，声源决定它何时何地发声。",
      },
      {
        title: "空间化与混音决定听感",
        focus: "距离、遮挡、总线和效果共同塑造最终声音。",
      },
      {
        title: "DSP 线程把声音安全送到设备",
        focus: "音频输出最怕等待和抖动，边界必须低延迟。",
      },
    ],
  }),
  gameplay: makeSpec({
    title: "游戏对象 / 组件 / 脚本 / 事件",
    subtitle:
      "玩法系统把对象生命周期、组件组合、脚本逻辑和事件流组织成可维护状态。",
    nodes: [
      {
        id: "object",
        label: "游戏对象",
        note: "身份和生命周期",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "component",
        label: "组件组合",
        note: "能力挂载",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "script",
        label: "脚本逻辑",
        note: "规则和条件",
        lane: "tools",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "event",
        label: "事件派发",
        note: "解耦系统交互",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "state",
        label: "状态更新",
        note: "世界状态改变",
        lane: "runtime",
        x: xs[4],
        tone: "output",
        step: 3,
      },
      {
        id: "save",
        label: "存档 / UI / 音效",
        note: "对外可见结果",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "组件边界变泥潭", x: 286, y: 214, tone: "risk", step: 1 },
      { label: "事件顺序隐式依赖", x: 530, y: 214, tone: "risk", step: 2 },
    ],
    steps: [
      {
        title: "对象和组件定义玩法实体",
        focus: "组合关系决定一个实体拥有哪些能力。",
      },
      {
        title: "脚本与事件驱动规则变化",
        focus: "玩法逻辑要通过清楚的事件和状态边界协作。",
      },
      {
        title: "状态结果影响存档和表现层",
        focus: "玩法更新最终会落到 UI、音效、存档或关卡状态。",
      },
    ],
  }),
  runtime: makeSpec({
    title: "关卡运行时服务",
    subtitle:
      "运行时玩法基础系统共享关卡状态，为任务、AI、相机、存档和网络提供稳定服务。",
    nodes: [
      {
        id: "level",
        label: "关卡状态",
        note: "实体、触发器、区域",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "quest",
        label: "任务 / 目标",
        note: "进度和条件",
        lane: "runtime",
        x: xs[1],
        step: 1,
      },
      {
        id: "ai",
        label: "AI / 导航",
        note: "感知与决策",
        lane: "runtime",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "camera",
        label: "相机 / 触发器",
        note: "视角与区域反馈",
        lane: "runtime",
        x: xs[3],
        step: 2,
      },
      {
        id: "save",
        label: "存档 / 网络",
        note: "持久化和同步",
        lane: "platform",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "world",
        label: "共享玩法状态",
        note: "可恢复、可同步",
        lane: "platform",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      {
        label: "关卡状态没有单一事实源",
        x: 250,
        y: 214,
        tone: "risk",
        step: 1,
      },
      {
        label: "网络同步和存档语义冲突",
        x: 670,
        y: 214,
        tone: "wait",
        step: 3,
      },
    ],
    steps: [
      {
        title: "关卡状态驱动任务和目标",
        focus: "任务系统必须知道世界里哪些事实已经成立。",
      },
      {
        title: "AI、相机和触发器消费同一世界",
        focus: "这些系统共享状态，但不能互相偷偷改写边界。",
      },
      {
        title: "存档和网络要求状态可解释",
        focus: "能保存、同步、恢复的状态才是真正稳定的运行时状态。",
      },
    ],
  }),
  more: makeSpec({
    title: "引擎架构扩展地图",
    subtitle:
      "前 16 章只是核心；真实引擎还会扩展到平台、编辑器、服务端、多人与生产管线。",
    nodes: [
      {
        id: "core",
        label: "核心运行时",
        note: "前文系统汇总",
        lane: "runtime",
        x: xs[0],
        tone: "data",
        step: 1,
      },
      {
        id: "platform",
        label: "平台专项",
        note: "主机、移动、PC",
        lane: "platform",
        x: xs[1],
        step: 1,
      },
      {
        id: "editor",
        label: "编辑器生态",
        note: "关卡、工具、插件",
        lane: "tools",
        x: xs[2],
        tone: "wait",
        step: 2,
      },
      {
        id: "services",
        label: "在线服务",
        note: "账号、遥测、内容",
        lane: "platform",
        x: xs[3],
        step: 2,
      },
      {
        id: "multiplayer",
        label: "多人游戏",
        note: "复制、预测、回滚",
        lane: "runtime",
        x: xs[4],
        tone: "risk",
        step: 3,
      },
      {
        id: "production",
        label: "生产管线",
        note: "团队规模化交付",
        lane: "tools",
        x: xs[5],
        tone: "output",
        step: 3,
      },
    ],
    risks: [
      { label: "核心边界过早绑定平台", x: 250, y: 214, tone: "risk", step: 1 },
      {
        label: "工具与服务缺少共同数据模型",
        x: 530,
        y: 114,
        tone: "wait",
        step: 2,
      },
    ],
    steps: [
      {
        title: "从核心运行时外扩到平台",
        focus: "先判断哪些能力属于核心，哪些应该被平台层吸收。",
      },
      {
        title: "编辑器和服务端改变生产方式",
        focus: "大型引擎不只是运行时，也是内容和服务生产系统。",
      },
      {
        title: "多人和生产管线检验架构弹性",
        focus: "扩展能力越多，越需要清晰的数据模型和边界。",
      },
    ],
  }),
};
