"use client";

import { useId, useState, type ReactNode } from "react";

export type GeometricMode = "roadmap" | "quadtree" | "range" | "bsp" | "bvh" | "distance" | "voronoi" | "proximity" | "kinetic" | "robust" | "dynamic";
export interface GeometricSnapshot { label: string; object: string; transform: string; certificate: string; warning: string }

export function GeometricDataOfficialLab({ title, caption, mode, snapshots, initial = 0 }: { title: string; caption: string; mode: GeometricMode; snapshots: ReadonlyArray<GeometricSnapshot>; initial?: number }) {
  const [selected, setSelected] = useState(Math.min(initial, snapshots.length - 1));
  const [size, setSize] = useState(7);
  const [query, setQuery] = useState(0.58);
  const marker = useId().replaceAll(":", "");
  const item = snapshots[selected];
  return <figure className="not-prose my-6"><div className="border border-border bg-elevated p-4"><div className="flex items-center justify-between gap-3 border-b border-border pb-3"><div><strong className="text-sm text-primary">{title}</strong><p className="mt-1 text-xs text-secondary">{caption}</p></div><button type="button" title="重置实验" aria-label="重置实验" onClick={() => { setSelected(initial); setSize(7); setQuery(0.58); }} className="grid size-9 place-items-center border border-border bg-bg text-lg text-secondary"><span aria-hidden="true">↺</span></button></div><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(16rem,.6fr)]"><div><svg viewBox="0 0 640 360" role="img" aria-label={title} className="aspect-video w-full border border-border bg-bg"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" className="fill-accent" /></marker></defs>{scene(mode, size, query, marker)}</svg><div className="mt-3 grid grid-cols-5 gap-1">{snapshots.map((snapshot, index) => <button key={snapshot.label} type="button" onClick={() => setSelected(index)} aria-pressed={index === selected} className={`min-h-14 border px-1 text-[11px] leading-4 ${index === selected ? "border-accent bg-accent/10 text-primary" : "border-border bg-bg text-secondary"}`}>{snapshot.label}</button>)}</div></div><div className="grid content-start gap-3"><Control label="对象规模" value={size} min={3} max={12} step={1} text={String(size)} set={setSize} /><Control label="查询范围" value={query} min={0.1} max={0.95} step={0.01} text={Math.round(query * 100) + "%"} set={setQuery} /><Cell label="对象" value={item.object} /><Cell label="变换" value={item.transform} /><Cell label="证书" value={item.certificate} /><div className="border border-rose-500/40 bg-rose-500/10 p-3 text-xs leading-5 text-primary"><b>边界：</b>{item.warning}</div></div></div></div></figure>;
}

function Control({ label, value, min, max, step, text, set }: { label: string; value: number; min: number; max: number; step: number; text: string; set: (value: number) => void }) { return <label className="grid gap-1 text-xs text-secondary"><span className="flex justify-between">{label}<b className="font-mono text-primary">{text}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={(event) => set(Number(event.target.value))} className="h-1 accent-cyan-500" /></label>; }
function Cell({ label, value }: { label: string; value: string }) { return <div className="min-h-20 border border-border bg-bg p-3"><span className="text-[11px] text-secondary">{label}</span><strong className="mt-1 block text-xs leading-5 text-primary">{value}</strong></div>; }

function scene(mode: GeometricMode, size: number, query: number, marker: string): ReactNode {
  const arrow = { markerEnd: `url(#${marker})` };
  const points = Array.from({ length: size }, (_, index) => ({ x: 85 + (index * 79) % 490, y: 72 + (index * 113) % 230 }));
  if (mode === "quadtree") return <g><rect x="55" y="35" width="530" height="290" className="fill-none stroke-cyan-500" strokeWidth="3" />{[320, 187, 452].map((x) => <line key={x} x1={x} y1="35" x2={x} y2="325" className="stroke-border" />)}{[180, 108, 252].map((y) => <line key={y} x1="55" y1={y} x2="585" y2={y} className="stroke-border" />)}{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="7" className="fill-amber-500 stroke-amber-500" />)}</g>;
  if (mode === "range") return <g>{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="7" className="fill-cyan-500 stroke-cyan-500" />)}<rect x={110 + query * 90} y={70 + query * 45} width={300 * query} height={210 * query} className="fill-emerald-500/10 stroke-emerald-500" strokeWidth="4" /></g>;
  if (mode === "bsp") return <g><line x1="90" y1="300" x2="540" y2="70" className="stroke-cyan-500" strokeWidth="5" /><line x1="145" y1="55" x2="460" y2="320" className="stroke-amber-500" strokeWidth="4" />{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="8" className={index % 2 ? "fill-emerald-500" : "fill-rose-500"} />)}</g>;
  if (mode === "bvh") return <g>{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="8" className="fill-primary" />)}<rect x="65" y="48" width="235" height="245" rx="4" className="fill-cyan-500/10 stroke-cyan-500" strokeWidth="4" /><rect x="275" y="75" width="300" height="225" rx="4" className="fill-amber-500/10 stroke-amber-500" strokeWidth="4" /></g>;
  if (mode === "distance") return <g>{Array.from({ length: 8 }, (_, index) => <circle key={index} cx="320" cy="180" r={24 + index * 18} className="fill-none stroke-cyan-500" opacity={1 - index * 0.09} />)}<path d="M250 210 C270 95 375 95 405 205 C365 270 285 270 250 210Z" className="fill-elevated stroke-amber-500" strokeWidth="4" /></g>;
  if (mode === "voronoi") return <g>{points.map((point, index) => <g key={index}><circle cx={point.x} cy={point.y} r="7" className="fill-amber-500" /><path d={`M${point.x - 35} ${point.y - 30} L${point.x + 45} ${point.y - 22} L${point.x + 32} ${point.y + 40} L${point.x - 42} ${point.y + 32} Z`} className="fill-cyan-500/5 stroke-cyan-500" /></g>)}</g>;
  if (mode === "proximity") return <g>{points.map((point, index) => <g key={index}>{index > 0 && <line x1={points[index - 1].x} y1={points[index - 1].y} x2={point.x} y2={point.y} className="stroke-emerald-500" strokeWidth="3" />}<circle cx={point.x} cy={point.y} r={10 + 7 * query} className="fill-cyan-500/20 stroke-cyan-500" /></g>)}</g>;
  if (mode === "kinetic") return <g>{points.map((point, index) => <g key={index}><circle cx={point.x + 35 * query} cy={point.y - 18 * query} r="9" className="fill-amber-500" /><line x1={point.x} y1={point.y} x2={point.x + 33 * query} y2={point.y - 17 * query} className="stroke-cyan-500" {...arrow} /></g>)}<line x1="90" y1="300" x2="555" y2="90" className="stroke-rose-500" strokeDasharray="8 6" /></g>;
  if (mode === "robust") return <g><line x1="80" y1="285" x2="560" y2="85" className="stroke-cyan-500" strokeWidth="5" />{points.map((point, index) => <circle key={index} cx={point.x} cy={180 + (index % 3 - 1) * (8 + 30 * query)} r="9" className={index % 3 === 1 ? "fill-rose-500" : "fill-emerald-500"} />)}<rect x="70" y={165 - 8 * query} width="500" height={30 + 16 * query} className="fill-amber-500/10 stroke-amber-500" /></g>;
  if (mode === "dynamic") return <g>{[0, 1, 2, 3].map((level) => <g key={level}><rect x={85 + level * 120} y={255 - level * 45} width={70 + level * 12} height={35 + level * 22} className="fill-cyan-500/10 stroke-cyan-500" strokeWidth="3" /><text x={120 + level * 124} y={278 - level * 38} textAnchor="middle" className="fill-primary text-xs">2^{level}</text></g>)}<path d="M100 110 H520" className="stroke-amber-500" strokeWidth="4" strokeDasharray="7 5" /></g>;
  return <g>{[90, 200, 320, 440, 550].map((x, index) => <g key={x}><circle cx={x} cy={index % 2 ? 115 : 245} r={24 + 9 * query} className={index === Math.floor(query * 5) % 5 ? "fill-cyan-500 stroke-cyan-500" : "fill-elevated stroke-border"} strokeWidth="3" />{index < 4 && <line x1={x + 28} y1={index % 2 ? 125 : 235} x2={x + 78} y2={(index + 1) % 2 ? 115 : 245} className="stroke-emerald-500" strokeWidth="3" {...arrow} />}</g>)}</g>;
}
