import type { ReviewQuestion } from "./types";

export const ctcSourceGeneratorsQuestions: ReviewQuestion[] = [
  {
    id: "ctc-source-generators-1",
    chapter: "ctc-source-generators",
    level: 1,
    question: "源生成器在什么阶段执行？它能做什么、不能做什么？",
    answer: "源生成器在编译时执行，不是运行时。它能分析编译中的代码（通过Roslyn API读取语法树和语义模型）并生成新的C#源代码加入编译。不能做的事：1）修改已有代码——只能添加新代码。2）使用运行时信息——不能读文件系统、环境变量、数据库。3）修改已编译的IL。生成的代码对用户可见（IDE可查看），需保证可读性。源生成器只能为partial class添加成员。",
    tags: ["源生成器", "编译时", "限制", "partial class"],
  },
  {
    id: "ctc-source-generators-2",
    chapter: "ctc-source-generators",
    level: 2,
    question: "源生成器比反射快在哪里？为什么生成的代码与手写代码一样快？",
    answer: "反射在运行时通过Type.GetProperties()、MethodInfo.Invoke()读取类型元数据——每次调用都遍历元数据表、检查可见性、构建反射对象、安全检查。源生成器在编译时分析类型，直接生成强类型代码——如直接person.Name访问而非prop.GetValue(person)。生成的代码与手写代码一样快：直接字段/属性访问，无元数据遍历，无装箱，无安全检查。性能差异可达10-100倍，且反射版本有GC分配（PropertyInfo[]等）。",
    tags: ["源生成器", "反射", "性能", "强类型"],
  },
  {
    id: "ctc-source-generators-3",
    chapter: "ctc-source-generators",
    level: 3,
    question: "增量源生成器（IIncrementalGenerator）比传统源生成器（ISourceGenerator）好在哪里？管线模型如何工作？",
    answer: "传统ISourceGenerator每次编译全量执行——即使只改一个字符，所有生成器Execute都重新运行。增量IIncrementalGenerator采用管线模型：1）ForAttributeWithMetadataName只在标记特定特性的语法变化时触发。2）SyntaxProvider.CreateSyntaxProvider按语法谓词过滤。3）Where/Select/Collect管线操作缓存中间结果。核心优势：增量计算——只改一个文件只重跑受影响阶段，其他阶段复用缓存。大型项目编译速度提升数倍。",
    tags: ["增量源生成器", "管线模型", "缓存", "编译速度"],
  },
  {
    id: "ctc-source-generators-4",
    chapter: "ctc-source-generators",
    level: 4,
    question: "设计一个源生成器场景：为标记 [GenerateToString] 的 class 自动生成 ToString 方法。说明生成器的工作流程和需要分析的信息。",
    answer: "工作流程：1）用ForAttributeWithMetadataName(\"MyApp.GenerateToStringAttribute\")找到所有标记该特性的类。2）对每个类，用语义模型获取所有公共属性（SymbolFinder或IPropertySymbol），收集属性名和类型。3）生成partial class代码，重写ToString返回$\"{ClassName} { Prop1 = {Prop1}, Prop2 = {Prop2} }\"格式。4）用context.AddSource(\"{ClassName}.ToString.g.cs\", source)添加到编译。需要分析的信息：类名、命名空间、公共属性列表（名称和类型）、是否有继承（base.ToString调用）。限制：类必须是partial，生成器不能修改已有成员只能添加新partial声明。生成的代码对用户可见应加// <auto-generated/>注释。",
    tags: ["源生成器设计", "GenerateToString", "Roslyn", "语义模型"],
  },
];
