"use client";

import { useMemo, useState } from "react";

export function Ec7ValueReferenceCopyLab() {
  const [reference,setReference]=useState(false); const [left,setLeft]=useState(10); const [right,setRight]=useState(10);
  const assign=()=>setRight(left); const mutate=()=>{ if(reference){setLeft(99);setRight(99);} else setRight(99); };
  return <figure className="mdx-figure not-prose mx-auto my-6"><div className="border border-border bg-elevated p-4 sm:p-5"><div className="grid grid-cols-2 border border-border">{[false,true].map(value=><button key={String(value)} type="button" onClick={()=>{setReference(value);setLeft(10);setRight(10);}} className={`min-h-11 text-sm ${reference===value?"bg-primary text-bg":"bg-bg text-primary"}`}>{value?"class reference":"struct value"}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="border border-cyan-500/40 bg-cyan-500/10 p-4 text-center"><span className="text-xs text-secondary">a</span><strong className="mt-2 block text-xl text-primary">{left}</strong></div><div className="border border-violet-500/40 bg-violet-500/10 p-4 text-center"><span className="text-xs text-secondary">b</span><strong className="mt-2 block text-xl text-primary">{right}</strong></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={assign} className="min-h-11 border border-border bg-bg text-sm text-primary">b = a</button><button type="button" onClick={mutate} className="min-h-11 border border-primary bg-primary text-sm text-bg">b.Value = 99</button></div><p className="mt-3 text-xs leading-5 text-secondary">{reference?"class assignment copies a reference; both names observe one object":"struct assignment copies the value; mutating b leaves a unchanged"}</p></div><figcaption className="mt-2 text-center text-sm text-secondary">切换struct/class并执行赋值与mutation，观察copy semantics与object identity。</figcaption></figure>;
}

const tupleCases=[
  {label:"named tuple",code:"(string Name, int Age) person = (\"Ada\", 36);",state:"fields available as person.Name and person.Age"},
  {label:"deconstruction",code:"(string name, int age) = person;",state:"two locals receive values by position"},
  {label:"discard",code:"(string name, _) = person;",state:"second element intentionally ignored"},
  {label:"nullable no value",code:"int? score = null;",state:"HasValue=false; Value would throw"},
  {label:"nullable value",code:"int? score = 0;",state:"HasValue=true; zero is distinct from null"},
];
export function Ec7NullableTupleLab(){const[selected,setSelected]=useState(0);const item=tupleCases[selected];return <figure className="mdx-figure not-prose mx-auto my-6"><div className="border border-border bg-elevated p-4 sm:p-5"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{tupleCases.map((entry,index)=><button key={entry.label} type="button" onClick={()=>setSelected(index)} className={`min-h-12 border px-2 text-xs ${selected===index?"border-amber-500 bg-amber-500/15 text-primary":"border-border bg-bg text-secondary"}`}>{entry.label}</button>)}</div><code className="mt-4 block min-h-20 border border-border bg-bg p-4 text-sm text-primary">{item.code}</code><p className="mt-3 border border-emerald-500/40 bg-emerald-500/10 p-3 text-sm text-primary">{item.state}</p></div><figcaption className="mt-2 text-center text-sm text-secondary">比较nullable状态与C# 7 tuple命名、deconstruction和discard。</figcaption></figure>}

const arrays=[
  {label:"one-dimensional",shape:"int[4]",indexes:"[0] … [3]",storage:"one contiguous logical sequence",cells:[["0","1","2","3"]]},
  {label:"rectangular",shape:"int[2,3]",indexes:"[row,column]",storage:"one rank-2 array with fixed rectangle",cells:[["0,0","0,1","0,2"],["1,0","1,1","1,2"]]},
  {label:"jagged",shape:"int[2][]",indexes:"[row][column]",storage:"array of array references; row lengths differ",cells:[["0,0","0,1"],["1,0","1,1","1,2","1,3"]]},
];
export function Ec7ArrayShapeLab(){const[selected,setSelected]=useState(1);const item=arrays[selected];const total=useMemo(()=>item.cells.reduce((n,row)=>n+row.length,0),[item]);return <figure className="mdx-figure not-prose mx-auto my-6"><div className="border border-border bg-elevated p-4 sm:p-5"><div className="grid grid-cols-3 border border-border">{arrays.map((entry,index)=><button key={entry.label} type="button" onClick={()=>setSelected(index)} className={`min-h-11 text-xs sm:text-sm ${selected===index?"bg-primary text-bg":"bg-bg text-primary"}`}>{entry.label}</button>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_2fr]"><div className="border border-border bg-bg p-3 text-sm leading-7 text-primary">type: {item.shape}<br/>index: {item.indexes}<br/>Length: {total}<br/><span className="text-xs text-secondary">{item.storage}</span></div><div className="space-y-2">{item.cells.map((row,rowIndex)=><div key={rowIndex} className="flex gap-2">{row.map(cell=><span key={cell} className="flex min-h-11 flex-1 items-center justify-center border border-cyan-500/40 bg-cyan-500/10 text-xs text-primary">{cell}</span>)}</div>)}</div></div></div><figcaption className="mt-2 text-center text-sm text-secondary">切换array shape，比较rank、index syntax、row lengths与Length含义。</figcaption></figure>}
