/**
 * Tpp20FinalReviewChainDiagram：程序员修炼之道全书跨章证据链。
 */
import {
  T,
  DiagramCaption,
  DiagramTitle,
} from "@/components/mdx/poeaa-enterprise-patterns/poeaa-svg-primitives";

const VIEW_W = 720;
const VIEW_H = 250;

export function Tpp20FinalReviewChainDiagram() {
  return (
    <figure className="mdx-figure mx-auto my-6">
      <div className="overflow-hidden rounded-card border border-border bg-elevated p-5">
        <svg
          viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
          role="img"
          aria-label="《程序员修炼之道（第2版）》全书总复习跨章证据链。个人责任进入设计反馈，工具证据缩短反馈，并发安全保护状态，最终由用户价值和伦理边界裁决；每条边记录所有者、输入、输出和失败升级。"
          className="mx-auto block h-auto w-full max-w-[720px]"
        >
          <DiagramTitle x={VIEW_W / 2} y={32} text="全书总复习：跨章证据链" />

          <rect
            x={34}
            y={70}
            width={126}
            height={92}
            rx="8"
            fill="#3FB97F"
            fillOpacity="0.07"
            stroke="#3FB97F"
            strokeWidth="1.2"
          />
          <text
            x={97}
            y={96}
            textAnchor="middle"
            fontSize="12"
            fontWeight="700"
            fill="#3FB97F"
          >
            个人责任
          </text>
          <text
            x={97}
            y={122}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            问题 / 边界
          </text>
          <text
            x={97}
            y={144}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            拒绝条件
          </text>

          <line
            x1={160}
            y1={116}
            x2={190}
            y2={116}
            stroke={T.accent}
            strokeWidth="1.4"
          />
          <rect
            x={190}
            y={70}
            width={126}
            height={92}
            rx="8"
            fill="#E5B567"
            fillOpacity="0.08"
            stroke="#E5B567"
            strokeWidth="1.2"
          />
          <text
            x={253}
            y={96}
            textAnchor="middle"
            fontSize="12"
            fontWeight="700"
            fill="#E5B567"
          >
            设计反馈
          </text>
          <text
            x={253}
            y={122}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            可变更性
          </text>
          <text
            x={253}
            y={144}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            用户信号
          </text>

          <line
            x1={316}
            y1={116}
            x2={346}
            y2={116}
            stroke={T.accent}
            strokeWidth="1.4"
          />
          <rect
            x={346}
            y={70}
            width={126}
            height={92}
            rx="8"
            fill="#D77A61"
            fillOpacity="0.08"
            stroke="#D77A61"
            strokeWidth="1.2"
          />
          <text
            x={409}
            y={96}
            textAnchor="middle"
            fontSize="12"
            fontWeight="700"
            fill="#D77A61"
          >
            工具与契约
          </text>
          <text
            x={409}
            y={122}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            快速反馈
          </text>
          <text
            x={409}
            y={144}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            非法状态拒绝
          </text>

          <line
            x1={472}
            y1={116}
            x2={502}
            y2={116}
            stroke={T.accent}
            strokeWidth="1.4"
          />
          <rect
            x={502}
            y={70}
            width={84}
            height={92}
            rx="8"
            fill={T.accent}
            fillOpacity="0.07"
            stroke={T.accent}
            strokeWidth="1.2"
          />
          <text
            x={544}
            y={96}
            textAnchor="middle"
            fontSize="12"
            fontWeight="700"
            fill={T.accent}
          >
            并发安全
          </text>
          <text
            x={544}
            y={122}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            所有权
          </text>
          <text
            x={544}
            y={144}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            状态边界
          </text>

          <line
            x1={586}
            y1={116}
            x2={608}
            y2={116}
            stroke={T.border}
            strokeWidth="1.2"
          />
          <rect
            x={608}
            y={70}
            width={78}
            height={92}
            rx="8"
            fill={T.primary}
            fillOpacity="0.04"
            stroke={T.border}
            strokeWidth="1.2"
          />
          <text
            x={647}
            y={96}
            textAnchor="middle"
            fontSize="12"
            fontWeight="700"
            fill={T.primary}
          >
            用户价值
          </text>
          <text
            x={647}
            y={122}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            结果
          </text>
          <text
            x={647}
            y={144}
            textAnchor="middle"
            fontSize="11"
            fill={T.secondary}
          >
            伦理
          </text>

          <rect
            x={104}
            y={192}
            width={512}
            height={28}
            rx="8"
            fill={T.primary}
            fillOpacity="0.03"
            stroke={T.border}
            strokeWidth="1"
          />
          <text
            x={360}
            y={211}
            textAnchor="middle"
            fontSize="11"
            fill={T.primary}
          >
            每条边：输入 → 所有者 → 状态变化 → 失败升级
          </text>

          <DiagramCaption
            x={VIEW_W / 2}
            y={VIEW_H - 10}
            text="跨章复习连接责任，不是把实践全量叠加"
          />
        </svg>
      </div>
      <figcaption className="mt-2 text-center text-sm text-secondary">
        总复习把章节语境串成证据链，最终仍由用户价值、质量和伦理边界裁决。
      </figcaption>
    </figure>
  );
}
