import manifest from "../../../../../quality/fidelity-manifests.json";
import type { ReactNode } from "react";
type Unit={id:string;title:string};
const units=manifest.books["real-time-rendering-4e"].units as Unit[];
const groups=[["Pipeline / Hardware","4","1-3, 23"],["Transform / Representation","3","4, 16-17"],["Shading / Forms","6","5, 8, 10, 13-15"],["Texture / Image","2","6, 12"],["Shadows","1","7"],["Physical Shading","1","9"],["Light Transport","2","11, 26"],["Systems / Acceleration","7","18-22, 24-25"]] as const;
function Frame({caption,children}:{caption:string;children:ReactNode}){return <figure className="mdx-figure not-prose mx-auto my-6"><div className="overflow-hidden rounded-card border border-border bg-elevated p-4 sm:p-5">{children}</div><figcaption className="mt-2 text-center text-sm text-secondary">{caption}</figcaption></figure>}
export function RtrLearningMapDiagram(){const layers=[["Frame","pipeline · GPU · hardware"],["Represent","transform · mesh · curve · volume"],["Appearance","shade · texture · color · style"],["Transport","shadow · GI · ray tracing"],["System","optimize · VR/AR · query · collision"]];return <Frame caption="第四版以五层系统连接 26 章，不止是从顶点到像素的单线流程。"><div role="img" aria-label="Real-Time Rendering 第四版五层体系" className="grid gap-2 md:grid-cols-5">{layers.map(([a,b],i)=><div key={a} className="grid min-h-24 content-center rounded-control border border-border bg-bg/45 p-3 text-center"><span className="text-xs font-bold text-accent">0{i+1}</span><strong className="mt-1 text-xs text-primary">{a}</strong><span className="mt-2 text-xs text-secondary">{b}</span></div>)}</div></Frame>}
export function RtrChapterMappingDiagram(){return <Frame caption="八个内容页主归属集合互不重叠，总数严格等于 26。"><div role="img" aria-label="官方二十六章到八个内容页的映射" className="overflow-hidden rounded-control border border-border text-xs"><div className="grid grid-cols-[1.4fr_.4fr_1.6fr] gap-px bg-border">{['Content page','Count','Official chapters'].map(x=><strong key={x} className="bg-bg p-3 text-primary">{x}</strong>)}{groups.flatMap(r=>r.map((x,i)=><span key={`${r[0]}-${x}`} className={i===0?"bg-accent/10 p-3 font-semibold text-accent":"bg-elevated p-3 text-secondary"}>{x}</span>))}</div></div></Frame>}
export function RtrOfficialInventoryDiagram(){return <Frame caption="26 个标题直接来自权威 manifest，与评分覆盖使用同一清单。"><div role="img" aria-label="Real-Time Rendering 第四版二十六章官方目录" className="grid gap-x-6 gap-y-1 md:grid-cols-2">{units.map(unit=><div key={unit.id} className="grid grid-cols-[3.6rem_1fr] border-b border-border/60 py-2 text-xs"><span className="font-mono font-semibold text-accent">{unit.id.toUpperCase()}</span><span className="text-secondary">{unit.title}</span></div>)}</div></Frame>}
