"use client";

import { useMemo, useState } from "react";
type Mode = "pipeline" | "experiment" | "evidence";
type Props = { mode: Mode; unitTitle: string; focus: string; nodes: string[] };
const phases = ["状态", "组合", "布局绘制", "输入导航", "产品结果"];
const scenarios = ["正常", "状态抖动", "错误身份", "所有者销毁", "版本漂移"];
const gates = ["目录结构", "状态结果", "生命周期", "可访问性", "迁移证据"];

export function OfficialJpc22BookLab({ mode, unitTitle, focus, nodes }: Props) {
  const [selected, setSelected] = useState(0); const [scenario, setScenario] = useState(0);
  const [stableKey, setStableKey] = useState(true); const [checked, setChecked] = useState([true, false, false, false, false]);
  const visible = nodes.slice(0, 32); const score = useMemo(() => checked.filter(Boolean).length * 20, [checked]);
  const result = scenario === 0 ? "保存行为基线" : scenario === 1 && stableKey ? "比较重组范围" : "拒绝交付并回滚";
  if (mode === "pipeline") return <section className="my-6 overflow-hidden rounded-md border border-zinc-300 bg-white text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "状态渲染管线"}><header className="border-b border-zinc-200 bg-emerald-50 px-4 py-3 dark:border-zinc-800 dark:bg-emerald-950/40"><p className="m-0 text-xs font-semibold uppercase text-emerald-800 dark:text-emerald-300">State to product pipeline</p><h3 className="m-0 mt-1 text-base font-bold">{unitTitle}</h3></header><div className="grid min-h-[340px] md:grid-cols-[minmax(0,1.25fr)_minmax(250px,0.75fr)]"><div className="grid content-start grid-cols-1 gap-2 border-b border-zinc-200 p-4 sm:grid-cols-2 md:border-b-0 md:border-r dark:border-zinc-800">{visible.map((node, index) => <button key={node} type="button" onClick={() => setSelected(index)} aria-pressed={selected === index} className={(selected === index ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-300 bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900") + " min-h-12 rounded border px-3 py-2 text-left text-xs font-medium"}>{String(index + 1).padStart(2, "0")} {node}</button>)}</div><div className="p-4"><p className="m-0 text-xs font-semibold text-rose-700 dark:text-rose-300">当前节点</p><p className="mt-2 min-h-12 text-sm font-bold">{visible[selected] ?? unitTitle}</p><div className="mt-4 grid grid-cols-5 gap-1">{phases.map((item) => <span key={item} className="flex min-h-12 items-center justify-center border px-1 text-center text-xs font-semibold">{item}</span>)}</div><p className="mt-4 text-sm leading-6">{focus}</p></div></div></section>;
  if (mode === "experiment") return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "反例实验"}><p className="m-0 text-xs font-semibold text-cyan-700 dark:text-cyan-300">State, owner and version experiment</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{scenarios.map((item, index) => <button key={item} type="button" onClick={() => setScenario(index)} aria-pressed={scenario === index} className={(scenario === index ? "border-cyan-700 bg-cyan-700 text-white" : "border-zinc-300 bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900") + " min-h-12 rounded border px-2 text-xs font-semibold"}>{item}</button>)}</div><button type="button" onClick={() => setStableKey((value) => !value)} className={(stableKey ? "border-zinc-300" : "border-rose-700 bg-rose-700 text-white") + " mt-4 min-h-11 rounded border px-3 text-sm"}>{stableKey ? "稳定身份" : "位置身份"}</button><p className="mt-4 text-2xl font-bold text-rose-700 dark:text-rose-300">{result}</p><p className="text-sm leading-6">{focus}</p></section>;
  return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "证据门"}><div className="flex items-center justify-between"><h3 className="m-0 text-base font-bold">Compose交付证据</h3><output className="rounded border px-3 py-2 text-lg font-bold">{score}%</output></div><div className="mt-4 divide-y border-y">{gates.map((gate, index) => <button key={gate} type="button" onClick={() => setChecked((current) => current.map((value, itemIndex) => itemIndex === index ? !value : value))} className="flex min-h-11 w-full items-center justify-between px-2 text-left text-sm"><span>{gate}</span><span>{checked[index] ? "通过" : "待补"}</span></button>)}</div><p className="mt-4 text-sm leading-6">{score === 100 ? "证据齐全，可以独立交接。" : "仍缺结构、状态、生命周期、可访问性或迁移证据。"}</p><p className="text-xs leading-5">{focus}</p></section>;
}
