import { OfficialCra4BookLab } from "./official-cra4-book-lab";

const nodes = [
  "第2章 Android应用的界面编程",
  "2.1 界面编程与视图（View）组件",
  "2.1.1 视图组件与容器组件",
  "2.1.2 使用XML布局文件控制UI界面",
  "2.1.3 在代码中控制UI界面",
  "实例：用编程的方式开发UI界面",
  "2.1.4 使用XML布局文件和代码混合控制UI界面",
  "实例：简单图片浏览器",
  "2.1.5 开发自定义View",
  "实例：跟随手指的小球",
  "2.2 第1组UI组件：布局管理器",
  "2.2.1 线性布局",
  "2.2.2 表格布局",
  "实例：丰富的表格布局",
  "2.2.3 帧布局",
  "实例：霓虹灯效果",
  "2.2.4 绝对布局",
  "2.2.5 约束布局",
  "2.3 第2组UI组件：TextView及其子类",
  "2.3.1 文本框（TextView）和编辑框（EditText）的功能与用法",
  "实例：功能丰富的文本框",
  "2.3.2 EditText的功能与用法",
  "2.3.3 按钮（Button）组件的功能与用法",
  "实例：按钮、圆形按钮、带文字的图片按钮",
  "2.3.4 使用9Patch图片作为背景",
  "2.3.5 单选钮（RadioButton）和复选框（CheckBox）的功能与用法",
  "实例：利用单选钮、复选框获取用户信息",
  "2.3.6 状态开关按钮（ToggleButton）和开关（Switch）的功能与用法",
  "实例：动态控制布局",
  "2.3.7 时钟（AnalogClock和TextClock）的功能与用法",
  "实例：手机里的“劳力士”",
  "2.3.8 计时器（Chronometer）",
  "2.4 第3组UI组件：ImageView及其子类",
  "实例：图片浏览器",
  "实例：强大的图片按钮",
  "实例：使用QuickContactBadge关联联系人",
  "实例：可折叠的悬浮按钮",
  "2.5 第4组UI组件：AdapterView及子类",
  "2.5.1 Adapter接口及实现类",
  "实例：使用ArrayAdapter创建ListView",
  "实例：使用SimpleAdapter创建ListView",
  "2.5.2 自动完成文本框（AutoCompleteTextView）的功能与用法",
  "2.5.3 可展开的列表组件（ExpandableListView）",
  "2.5.4 Spinner的功能与用法",
  "2.5.5 AdapterViewFlipper的功能与用法",
  "实例：自动播放的图片库",
  "2.5.6 StackView的功能与用法",
  "实例：叠在一起的图片",
  "2.5.7 优秀的RecyclerView组件",
  "实例：使用RecyclerView实现列表",
  "2.6 第5组UI组件：ProgressBar及其子类",
  "2.6.1 进度条（ProgressBar）的功能与用法",
  "2.6.2 拖动条（SeekBar）的功能与用法",
  "实例：通过拖动滑块来改变图片的透明度",
  "2.6.3 星级评分条（RatingBar）的功能与用法",
  "实例：通过星级改变图片的透明度",
  "2.7 第6组UI组件：ViewAnimator及其子类",
  "2.7.1 ViewSwitcher的功能与用法",
  "实例：仿Android系统的Launcher界面",
  "2.7.2 图像切换器（ImageSwitcher）的功能与用法",
  "实例：支持动画的图片浏览器",
  "2.7.3 文本切换器（TextSwitcher）的功能与用法",
  "2.7.4 ViewFlipper的功能与用法",
  "实例：自动播放的图片库",
  "2.8 各种杂项组件",
  "2.8.1 使用Toast显示提示信息框",
  "实例：带图片的消息提示",
  "2.8.2 日历视图（CalendarView）组件的功能与用法",
  "实例：选择您的生日",
  "2.8.3 日期、时间选择器（DatePicker和TimePicker）的功能与用法",
  "实例：用户选择日期、时间",
  "2.8.4 数值选择器（NumberPicker）的功能与用法",
  "实例：选择您意向的价格范围",
  "2.8.5 搜索框（SearchView）的功能与用法",
  "实例：搜索",
  "2.8.6 滚动视图（ScrollView）的功能与用法",
  "实例：可垂直和水平滚动的视图",
  "2.8.7 Android 9 改进的通知和通知Channel",
  "实例：加薪通知",
  "2.9 第7组UI组件：对话框",
  "2.9.1 使用AlertDialog创建对话框",
  "实例：显示提示消息的对话框",
  "实例：简单列表项对话框",
  "实例：单选列表项对话框",
  "实例：多选列表项对话框",
  "实例：自定义列表项对话框",
  "实例：自定义View对话框",
  "2.9.2 对话框风格的窗口",
  "2.9.3 使用PopupWindow",
  "2.9.4 使用DatePickerDialog、TimePickerDialog",
  "2.9.5 使用ProgressDialog创建进度对话框",
  "2.10 菜单",
  "2.10.1 选项菜单和子菜单（SubMenu）",
  "2.10.2 使用监听器来监听菜单事件",
  "2.10.3 创建多选菜单项和单选菜单项",
  "2.10.4 设置与菜单项关联的Activity",
  "2.10.5 上下文菜单",
  "2.10.6 使用XML文件定义菜单",
  "实例：使用XML资源文件定义菜单",
  "2.10.7 使用PopupMenu创建弹出式菜单",
  "2.11 使用活动条（ActionBar）",
  "2.11.1 启用ActionBar",
  "2.11.2 使用ActionBar显示选项菜单项",
  "2.11.3 启用程序图标导航",
  "2.11.4 添加Action View",
  "实例：“标题”上的时钟",
  "2.12 本章小结"
];

export function CraLifecycleLab() { return <OfficialCra4BookLab mode="lifecycle" unitTitle="第2章 Android应用的界面编程" focus="从View树、布局管理器、控件族、AdapterView、对话框、菜单和ActionBar构造完整传统View界面" nodes={nodes} />; }
export function CraFailureLab() { return <OfficialCra4BookLab mode="failure" unitTitle="第2章 Android应用的界面编程" focus="从View树、布局管理器、控件族、AdapterView、对话框、菜单和ActionBar构造完整传统View界面" nodes={nodes} />; }
export function CraEvidenceLab() { return <OfficialCra4BookLab mode="evidence" unitTitle="第2章 Android应用的界面编程" focus="View树、约束与测量记录、控件状态矩阵、列表回收轨迹和无障碍检查" nodes={nodes} />; }
