"use client";
import { useMemo, useState } from "react";
type Mode = "lifecycle" | "state" | "evidence";
type Props = { mode: Mode; unitTitle: string; focus: string; nodes: string[] };
const stages = ["创建", "前台", "后台", "重建", "进程恢复"];
const gates = ["版本与设备", "生命周期", "持久状态", "失败与安全", "测试与发布"];
export function OfficialFla3BookLab({ mode, unitTitle, focus, nodes }: Props) {
  const [selected, setSelected] = useState(0); const [stage, setStage] = useState(1); const [network, setNetwork] = useState(true); const [permission, setPermission] = useState(true); const [checked, setChecked] = useState([true, false, false, false, false]);
  function resetExperiment() {
    setSelected(0);
    setStage(1);
    setNetwork(true);
    setPermission(true);
    setChecked([true, false, false, false, false]);
  }

  const visible = nodes.slice(0, 16); const score = useMemo(() => checked.filter(Boolean).length * 20, [checked]); const risk = (stage >= 3 ? 35 : 5) + (!network ? 25 : 0) + (!permission ? 30 : 0);
  if (mode === "lifecycle") return <section className="my-6 overflow-hidden rounded-md border border-zinc-300 bg-white text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "章节与生命周期图"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><header className="border-b border-zinc-200 bg-emerald-50 px-4 py-3 dark:border-zinc-800 dark:bg-emerald-950/40"><p className="m-0 text-xs font-semibold uppercase text-emerald-800 dark:text-emerald-300">Chapter and lifecycle map</p><h3 className="m-0 mt-1 text-base font-bold">{unitTitle}</h3></header><div className="grid min-h-[300px] md:grid-cols-[minmax(0,1.15fr)_minmax(240px,0.85fr)]"><div className="grid content-start grid-cols-1 gap-2 border-b border-zinc-200 p-4 sm:grid-cols-2 md:border-b-0 md:border-r dark:border-zinc-800">{visible.map((node, index) => <button key={node} type="button" onClick={() => setSelected(index)} aria-pressed={selected === index} className={"min-h-12 rounded border px-3 py-2 text-left text-xs font-medium " + (selected === index ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-300 bg-zinc-50 text-zinc-800 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100")}><span className="mr-2 font-mono">{String(index + 1).padStart(2, "0")}</span>{node}</button>)}</div><div className="p-4"><p className="m-0 text-xs font-semibold text-rose-700 dark:text-rose-300">当前节点</p><p className="mt-2 min-h-12 text-sm font-bold">{visible[selected] ?? unitTitle}</p><p className="mt-3 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p><p className="mt-4 border-l-4 border-amber-500 pl-3 text-xs leading-5 text-zinc-600 dark:text-zinc-400">每个API都要落回所有者、状态、回调线程与销毁时刻。</p></div></div></section>;
  if (mode === "state") return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "状态恢复实验"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><p className="m-0 text-xs font-semibold text-cyan-700 dark:text-cyan-300">State and failure lab</p><h3 className="m-0 mt-1 text-base font-bold">生命周期与外部条件</h3><div className="mt-4 grid grid-cols-5 gap-1">{stages.map((item,index)=><button key={item} type="button" onClick={()=>setStage(index)} aria-pressed={stage===index} className={"min-h-12 rounded border px-1 text-xs font-semibold "+(stage===index?"border-cyan-700 bg-cyan-700 text-white":"border-zinc-300 bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900")}>{item}</button>)}</div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>setNetwork(v=>!v)} aria-pressed={!network} className={"min-h-11 rounded border px-3 text-sm "+(!network?"border-rose-700 bg-rose-700 text-white":"border-zinc-300 dark:border-zinc-700")}>{network?"网络可用":"网络中断"}</button><button type="button" onClick={()=>setPermission(v=>!v)} aria-pressed={!permission} className={"min-h-11 rounded border px-3 text-sm "+(!permission?"border-amber-700 bg-amber-700 text-white":"border-zinc-300 dark:border-zinc-700")}>{permission?"权限允许":"权限拒绝"}</button></div><div className="mt-4 rounded border border-zinc-300 p-3 dark:border-zinc-700"><p className="m-0 text-xs text-zinc-500">未处理状态风险</p><p className="m-0 mt-1 text-2xl font-bold text-rose-700 dark:text-rose-300">{risk}%</p></div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p></section>;
  return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "证据门"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><div className="flex items-center justify-between gap-3"><div><p className="m-0 text-xs font-semibold text-violet-700 dark:text-violet-300">Evidence gate</p><h3 className="m-0 mt-1 text-base font-bold">Android交付证据</h3></div><output className="min-w-16 rounded border border-zinc-300 px-3 py-2 text-center text-lg font-bold dark:border-zinc-700">{score}%</output></div><div className="mt-4 divide-y divide-zinc-200 border-y border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800">{gates.map((gate,index)=><button key={gate} type="button" onClick={()=>setChecked(c=>c.map((v,i)=>i===index?!v:v))} aria-pressed={checked[index]} className="flex min-h-11 w-full items-center justify-between gap-3 px-2 text-left text-sm hover:bg-zinc-50 dark:hover:bg-zinc-900"><span>{gate}</span><span className={"inline-flex h-6 w-6 items-center justify-center rounded border font-bold "+(checked[index]?"border-emerald-700 bg-emerald-700 text-white":"border-zinc-400 text-transparent")}>✓</span></button>)}</div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{score===100?"证据齐全：换设备、API级与故障条件独立重放。":"仍缺环境、生命周期、状态、失败或发布证据。"}</p><p className="mt-2 text-xs leading-5 text-zinc-600 dark:text-zinc-400">{focus}</p></section>;
}
