"use client";

import { useId, useState, type ReactNode } from "react";

export type ShaderMode = "roadmap" | "pipeline" | "shader" | "math" | "lighting" | "texture" | "transparent" | "effect" | "post" | "depth" | "npr" | "performance" | "pbr";
export interface ShaderSnapshot { label: string; stage: string; action: string; evidence: string; warning: string }

export function UnityShaderBookLab({ title, caption, mode, snapshots, initial = 0 }: { title: string; caption: string; mode: ShaderMode; snapshots: ReadonlyArray<ShaderSnapshot>; initial?: number }) {
  const [selected, setSelected] = useState(Math.min(initial, snapshots.length - 1));
  const [light, setLight] = useState(0.68);
  const [detail, setDetail] = useState(6);
  const marker = useId().replaceAll(":", "");
  const item = snapshots[selected];
  return <figure className="not-prose my-6"><div className="border border-border bg-elevated p-4"><div className="flex items-center justify-between gap-3 border-b border-border pb-3"><div><strong className="text-sm text-primary">{title}</strong><p className="mt-1 text-xs text-secondary">{caption}</p></div><button type="button" aria-label="重置实验" title="重置实验" onClick={() => { setSelected(initial); setLight(0.68); setDetail(6); }} className="grid size-11 place-items-center border border-border bg-bg text-lg text-secondary"><span aria-hidden="true">↺</span></button></div><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(16rem,.6fr)]"><div><svg viewBox="0 0 640 360" role="img" aria-label={title} className="aspect-video w-full border border-border bg-bg"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" className="fill-accent" /></marker></defs>{scene(mode, light, detail, marker)}</svg><div className="mt-3 grid grid-cols-5 gap-1">{snapshots.map((snapshot, index) => <button key={snapshot.label} type="button" onClick={() => setSelected(index)} aria-pressed={index === selected} className={`min-h-14 border px-1 text-[11px] leading-4 ${index === selected ? "border-accent bg-accent/10 text-primary" : "border-border bg-bg text-secondary"}`}>{snapshot.label}</button>)}</div></div><div className="grid content-start gap-3"><Control label="光照/阈值" value={light} min={0.05} max={1} step={0.01} text={Math.round(light * 100) + "%"} set={setLight} /><Control label="采样/复杂度" value={detail} min={2} max={12} step={1} text={String(detail)} set={setDetail} /><Cell label="阶段" value={item.stage} /><Cell label="操作" value={item.action} /><Cell label="证据" value={item.evidence} /><div className="border border-rose-500/40 bg-rose-500/10 p-3 text-xs leading-5 text-primary"><b>边界：</b>{item.warning}</div></div></div></div></figure>;
}

function Control({ label, value, min, max, step, text, set }: { label: string; value: number; min: number; max: number; step: number; text: string; set: (value: number) => void }) { return <label className="grid gap-1 text-xs text-secondary"><span className="flex justify-between">{label}<b className="font-mono text-primary">{text}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={(event) => set(Number(event.target.value))} className="h-1 accent-cyan-500" /></label>; }
function Cell({ label, value }: { label: string; value: string }) { return <div className="min-h-20 border border-border bg-bg p-3"><span className="text-[11px] text-secondary">{label}</span><strong className="mt-1 block text-xs leading-5 text-primary">{value}</strong></div>; }

function scene(mode: ShaderMode, light: number, detail: number, marker: string): ReactNode {
  const arrow = { markerEnd: `url(#${marker})` };
  if (mode === "pipeline" || mode === "roadmap") return <g>{[70, 185, 300, 415, 530].map((x, index) => <g key={x}><rect x={x - 40} y={index % 2 ? 90 : 220} width="80" height="48" className={index === Math.floor(light * 5) % 5 ? "fill-cyan-500 stroke-cyan-500" : "fill-elevated stroke-border"} /><text x={x} y={index % 2 ? 119 : 249} textAnchor="middle" className="fill-primary text-xs">{["CPU", "Vertex", "Raster", "Fragment", "Output"][index]}</text>{index < 4 && <line x1={x + 42} y1={index % 2 ? 115 : 235} x2={x + 72} y2={(index + 1) % 2 ? 115 : 235} className="stroke-emerald-500" strokeWidth="3" {...arrow} />}</g>)}</g>;
  if (mode === "math") return <g><line x1="320" y1="40" x2="320" y2="320" className="stroke-border" /><line x1="70" y1="180" x2="570" y2="180" className="stroke-border" /><line x1="320" y1="180" x2={320 + 190 * light} y2={180 - 120 * light} className="stroke-cyan-500" strokeWidth="6" {...arrow} /><line x1="320" y1="180" x2={320 - 90 * light} y2={180 - 170 * light} className="stroke-amber-500" strokeWidth="6" {...arrow} /></g>;
  if (mode === "lighting" || mode === "pbr") return <g><circle cx="320" cy="190" r="112" className="fill-elevated stroke-border" strokeWidth="4" /><path d={`M208 190 A112 112 0 0 1 432 190 A112 112 0 0 1 208 190`} className="fill-cyan-500/20 stroke-cyan-500" /><circle cx={265 + 110 * light} cy={135 - 40 * light} r={18 + 26 * light} className="fill-amber-500 stroke-amber-500" /><line x1="540" y1="65" x2="400" y2="145" className="stroke-amber-500" strokeWidth="5" {...arrow} /></g>;
  if (mode === "texture" || mode === "effect" || mode === "npr") return <g>{Array.from({ length: detail }, (_, row) => Array.from({ length: detail }, (_, column) => <rect key={row + "-" + column} x={105 + column * (420 / detail)} y={45 + row * (270 / detail)} width={420 / detail} height={270 / detail} className={(row + column) % 2 ? "fill-cyan-500/20 stroke-border" : "fill-amber-500/20 stroke-border"} opacity={0.45 + light * 0.5} />))}<path d="M90 290 C205 170 300 310 550 80" className="fill-none stroke-rose-500" strokeWidth="5" /></g>;
  if (mode === "transparent") return <g><rect x="115" y="70" width="290" height="215" className="fill-cyan-500/30 stroke-cyan-500" strokeWidth="5" /><rect x="245" y="110" width="290" height="215" className="fill-amber-500/30 stroke-amber-500" strokeWidth="5" opacity={light} /><text x="320" y="345" textAnchor="middle" className="fill-primary text-sm">Blend + depth order</text></g>;
  if (mode === "post" || mode === "depth") return <g>{Array.from({ length: detail }, (_, index) => <rect key={index} x={65 + index * (510 / detail)} y={70 + 160 * Math.sin(index * 0.8) * light / 2} width={510 / detail - 4} height={180 - 80 * light} className="fill-cyan-500/20 stroke-cyan-500" />)}<path d="M70 250 C180 65 360 315 570 95" className="fill-none stroke-amber-500" strokeWidth="6" /></g>;
  if (mode === "performance") return <g>{["CPU", "Vertex", "Fragment", "Bandwidth"].map((label, index) => { const h = 45 + ((index + detail) % 4) * 42 * light; return <g key={label}><rect x={95 + index * 125} y={300 - h} width="76" height={h} className={index === detail % 4 ? "fill-rose-500/40 stroke-rose-500" : "fill-cyan-500/20 stroke-cyan-500"} /><text x={133 + index * 125} y="325" textAnchor="middle" className="fill-primary text-xs">{label}</text></g>; })}</g>;
  return <g><rect x="100" y="65" width="440" height="230" className="fill-elevated stroke-border" strokeWidth="4" /><circle cx="260" cy="180" r={55 + 25 * light} className="fill-cyan-500/30 stroke-cyan-500" /><path d="M330 120 L480 180 L330 240Z" className="fill-amber-500/30 stroke-amber-500" /></g>;
}
