"use client";

import { useMemo, useState } from "react";
import type { ReactNode } from "react";

const accent = "var(--accent)";
const success = "var(--success)";
const warning = "var(--warning)";
const danger = "var(--danger)";
const primary = "var(--text-primary)";
const secondary = "var(--text-secondary)";
const border = "var(--border)";
const surface = "var(--surface)";

function Frame({ ariaLabel, caption, children }: { ariaLabel: string; caption: string; children: ReactNode }) {
  return <figure className="mdx-figure not-prose mx-auto my-6"><div className="overflow-hidden rounded-card border border-border bg-elevated p-5"><svg viewBox="0 0 720 390" role="img" aria-label={ariaLabel} className="mx-auto block h-auto w-full max-w-[720px]">{children}</svg></div><figcaption className="mt-2 text-center text-sm text-secondary">{caption}</figcaption></figure>;
}
function Arrow({ x1, y1, x2, y2, color = accent }: { x1: number; y1: number; x2: number; y2: number; color?: string }) { return <><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth={2.5}/><path d={`M ${x2 - 8} ${y2 - 5} L ${x2} ${y2} L ${x2 - 8} ${y2 + 5}`} fill="none" stroke={color} strokeWidth={2.5}/></>; }

export function GpuGems2Ch07SubdivisionDiagram() {
  return <Frame ariaLabel="Catmull-Clark subdivision：控制网格经过规则细分得到更平滑的 patch" caption="控制网格是紧凑的输入；重复 subdivision 让曲面更密、更接近 limit surface。"><text x={36} y={34} fontSize={14} fontWeight={700} fill={primary}>Control mesh → Catmull-Clark subdivision → smooth patch</text><g transform="translate(58 94)"><rect width={218} height={184} rx={16} fill={surface} stroke={accent} strokeWidth={2}/><text x={109} y={30} textAnchor="middle" fontSize={14} fontWeight={700} fill={accent}>control mesh</text><path d="M 38 138 L 82 66 L 142 52 L 178 132 L 118 160 Z" fill={accent} fillOpacity={0.1} stroke={accent} strokeWidth={2}/>{[[38,138],[82,66],[142,52],[178,132],[118,160]].map(([x,y], index) => <circle key={index} cx={x} cy={y} r={5} fill={accent}/>) }<text x={109} y={170} textAnchor="middle" fontSize={12} fill={secondary}>少量控制点</text></g><Arrow x1={300} y1={184} x2={360} y2={184}/><g transform="translate(382 94)"><rect width={280} height={184} rx={16} fill={surface} stroke={success} strokeWidth={2}/><text x={140} y={30} textAnchor="middle" fontSize={14} fontWeight={700} fill={success}>subdivided patch</text>{Array.from({length: 5}, (_, index) => <path key={`v-${index}`} d={`M ${38 + index * 48} 55 L ${38 + index * 48} 145`} stroke={success} strokeOpacity={0.55}/>) }{Array.from({length: 4}, (_, index) => <path key={`h-${index}`} d={`M 38 ${55 + index * 23} L 230 ${55 + index * 23}`} stroke={success} strokeOpacity={0.55}/>) }<path d="M 38 145 Q 140 35 230 145" fill="none" stroke={warning} strokeWidth={3}/><text x={140} y={170} textAnchor="middle" fontSize={12} fill={secondary}>规则网格 + 平滑曲面</text></g></Frame>;
}

export function GpuGems2Ch07AdaptiveFlatnessDiagram() {
  return <Frame ariaLabel="adaptive tessellation 根据屏幕像素中的 flatness 和曲率决定继续细分或输出" caption="近处或弯曲处继续细分，远处或平坦处停止；相同模型不必处处使用相同细分级别。"><text x={36} y={34} fontSize={14} fontWeight={700} fill={primary}>Flatness test：误差进入屏幕像素空间</text><g transform="translate(56 82)"><rect width={250} height={202} rx={16} fill={surface} stroke={success}/><text x={125} y={30} textAnchor="middle" fontSize={14} fontWeight={700} fill={success}>flat / far</text><path d="M 30 144 L 84 92 L 136 112 L 216 76" fill="none" stroke={success} strokeWidth={3}/><line x1={30} y1={152} x2={216} y2={152} stroke={border}/><text x={125} y={180} textAnchor="middle" fontSize={12} fill={secondary}>误差低于阈值 → stop</text></g><Arrow x1={330} y1={184} x2={386} y2={184}/><g transform="translate(412 82)"><rect width={250} height={202} rx={16} fill={surface} stroke={danger}/><text x={125} y={30} textAnchor="middle" fontSize={14} fontWeight={700} fill={danger}>curved / near</text><path d="M 30 146 Q 70 36 112 146 Q 160 34 216 146" fill="none" stroke={danger} strokeWidth={3}/><line x1={30} y1={152} x2={216} y2={152} stroke={border}/><text x={125} y={180} textAnchor="middle" fontSize={12} fill={secondary}>误差高于阈值 → subdivide</text></g><text x={360} y={342} textAnchor="middle" fontSize={13} fill={secondary}>flatness 以屏幕像素衡量，避免远处过密、近处不足</text></Frame>;
}

export function GpuGems2Ch07GpuPipelineDiagram() {
  const steps = [["Patch texture", "控制点 + ring", accent], ["Flatness", "边缘误差", warning], ["Subdivide", "shader 生成下一层", success], ["Limit attrs", "位置 + normal", danger]] as const;
  return <Frame ariaLabel="GPU 自适应细分流水线：patch texture、flatness test、subdivision、limit position and normal" caption="patch buffer 在纹理间 ping-pong；CPU 只管理 buffer 和索引，不触碰每个顶点数据。"><text x={36} y={34} fontSize={14} fontWeight={700} fill={primary}>GPU tessellation：patch buffer 之间反复筛选与细分</text><g transform="translate(40 96)">{steps.map(([title, detail, color], index) => <g key={title} transform={`translate(${index * 165} 0)`}><rect width={136} height={160} rx={16} fill={surface} stroke={color} strokeWidth={2}/><text x={68} y={50} textAnchor="middle" fontSize={14} fontWeight={700} fill={color}>{title}</text><text x={68} y={92} textAnchor="middle" fontSize={12} fill={secondary}>{detail.split(" + ")[0]}</text><text x={68} y={114} textAnchor="middle" fontSize={12} fill={secondary}>{detail.split(" + ")[1] || ""}</text><rect x={26} y={136} width={84} height={9} rx={4} fill={color} fillOpacity={0.2}/></g>)}</g><Arrow x1={180} y1={176} x2={204} y2={176}/><Arrow x1={345} y1={176} x2={369} y2={176} color={warning}/><Arrow x1={510} y1={176} x2={534} y2={176} color={success}/><text x={360} y={324} textAnchor="middle" fontSize={13} fill={secondary}>不平的 patch 写入下一层；平的 patch 直接计算最终属性</text></Frame>;
}

export function GpuGems2Ch07WatertightDiagram() {
  return <Frame ariaLabel="watertight adaptive tessellation：相邻 patch 边缘共享索引并处理 T-junction，避免裂缝" caption="自适应深度不同并不等于允许出现缝；索引构建阶段要统一共享边和 T-junction。"><text x={36} y={34} fontSize={14} fontWeight={700} fill={primary}>Watertightness：adaptive depth 变化也不能露缝</text><g transform="translate(84 78)"><path d="M 0 190 L 0 50 L 220 50 L 220 190 Z" fill={success} fillOpacity={0.08} stroke={success} strokeWidth={2}/><path d="M 220 190 L 220 98 L 440 98 L 440 190 Z" fill={accent} fillOpacity={0.08} stroke={accent} strokeWidth={2}/><line x1={220} y1={50} x2={220} y2={190} stroke={warning} strokeWidth={3}/><circle cx={220} cy={98} r={7} fill={warning}/><path d="M 198 98 L 220 98 L 242 98" stroke={warning} strokeWidth={3}/><text x={110} y={226} textAnchor="middle" fontSize={12} fill={success}>patch A：深</text><text x={330} y={226} textAnchor="middle" fontSize={12} fill={accent}>patch B：浅</text><text x={220} y={270} textAnchor="middle" fontSize={12} fill={warning}>共享边 / T-junction → 复用远边索引补三角形</text></g><rect x={98} y={322} width={524} height={30} rx={8} fill={surface} stroke={border}/><text x={360} y={342} textAnchor="middle" fontSize={12} fill={secondary}>不要依赖相邻 shader 浮点计算恰好一致</text></Frame>;
}

export function GpuGems2Ch07AdaptiveTessellationLab() {
  const [distance, setDistance] = useState(46);
  const [curvature, setCurvature] = useState(60);
  const [displacement, setDisplacement] = useState(28);
  const count = useMemo(() => Math.max(2, Math.min(7, Math.round(2 + curvature * 0.035 + (100 - distance) * 0.025 + displacement * 0.015))), [distance, curvature, displacement]);
  function reset() { setDistance(46); setCurvature(60); setDisplacement(28); }
  return <section className="not-prose my-8 overflow-hidden rounded-card border border-border bg-elevated" aria-label="GPU Gems 2 Chapter 7 adaptive tessellation 实验：调整距离、曲率和 displacement" data-visual-kind="gpu-gems2-ch07-adaptive-tessellation"><div className="border-b border-border px-5 py-4"><p className="text-sm font-semibold text-primary">Adaptive tessellation 实验</p><p className="mt-1 text-sm text-secondary">在屏幕误差阈值下，近处、弯曲处和 displacement 区域需要更多细分。</p></div><div className="grid gap-5 p-5 lg:grid-cols-[1fr_230px]"><div className="overflow-hidden rounded-card border border-border bg-[var(--bg)] p-3"><svg viewBox="0 0 540 330" role="img" aria-label="自适应细分网格预览" className="block h-auto w-full"><text x={270} y={25} textAnchor="middle" fontSize={13} fontWeight={700} fill={primary}>patch preview · subdivision level {count}</text><rect x={22} y={48} width={496} height={210} rx={15} fill={surface} stroke={border}/>{Array.from({length: count + 1}, (_, index) => <line key={`v-${index}`} x1={62 + index * (416 / count)} y1={70} x2={62 + index * (416 / count)} y2={236} stroke={index < count / 2 ? success : accent} strokeOpacity={0.52}/>) }{Array.from({length: count + 1}, (_, index) => <line key={`h-${index}`} x1={62} y1={70 + index * (166 / count)} x2={478} y2={70 + index * (166 / count)} stroke={border} strokeOpacity={0.52}/>) }<path d="M 62 196 Q 174 104 270 180 T 478 160" fill="none" stroke={warning} strokeWidth={3}/><text x={270} y={287} textAnchor="middle" fontSize={12} fill={secondary}>屏幕距离 {distance}% · 曲率 {curvature}% · displacement {displacement}%</text></svg></div><div className="space-y-4"><label className="block text-sm text-secondary">距离（越小越近）：{distance}%<input className="mt-2 block h-11 w-full accent-[var(--accent)]" type="range" min="0" max="100" value={distance} onChange={(event) => setDistance(Number(event.target.value))}/></label><label className="block text-sm text-secondary">曲率：{curvature}%<input className="mt-2 block h-11 w-full accent-[var(--accent)]" type="range" min="0" max="100" value={curvature} onChange={(event) => setCurvature(Number(event.target.value))}/></label><label className="block text-sm text-secondary">最大 displacement：{displacement}%<input className="mt-2 block h-11 w-full accent-[var(--accent)]" type="range" min="0" max="100" value={displacement} onChange={(event) => setDisplacement(Number(event.target.value))}/></label><p className="rounded-md border border-border bg-[var(--bg)] p-3 text-xs leading-5 text-secondary" aria-live="polite">当前级别 {count}。displacement 会加入 flatness error，不能只按原始曲率决定细分。</p><button type="button" className="min-h-11 w-full rounded-md border border-border px-3 py-2 text-sm font-semibold text-primary transition hover:border-[var(--accent)]" onClick={reset}>重置</button></div></div></section>;
}
