import { ConstructionMechanismLab } from "./construction-mechanism-lab";

const profile = {
  unitId: "cc2e-26-code-tuning-techniques",
  title: "第26章：代码调整方法",
  nodes: ["已证热点", "技术选择", "单点改写", "基准复测", "可移植性审查"],
  concepts: [
    "第26章 代码调整方法",
    "26.1 逻辑",
    "在知道答案后停止判断",
    "按照出现频率来调整判断顺序",
    "相似逻辑结构之间的性能比较",
    "用查找表替代复杂表达式",
    "使用惰性求值",
    "26.2 循环",
    "将判断外提（Unswitching）",
    "合并循环",
    "展开",
    "尽可能减少再循环内部做的工作",
    "哨兵值",
    "把最忙的循环放在最内层",
    "削减强度",
    "26.3 数据变换",
    "使用整型数而不是浮点数",
    "数组维度尽可能少",
    "尽可能减少数组引用",
    "使用辅助索引",
    "使用缓存机制",
    "26.4 表达式",
    "利用代数恒等式",
    "削弱运算强度",
    "编译时初始化",
    "小心系统函数",
    "使用正确的常量类型",
    "预先算出结果",
    "删除公共子表达式",
    "26.5 子程序",
    "将函数重写为内联",
    "26.6 用低级语言重写代码",
    "26.7 变得越多，事情反而更没变",
    "推荐读物",
    "关键点",
  ],
  mechanism:
    "调整技术针对已证热点改变逻辑、循环、数据变换、表达式或低级操作，一次只改一项并检查正确性、可读性与可移植性",
  success: "第26章：代码调整方法 的机制链、结果和复位轨迹与预测一致",
  failure:
    "第26章：代码调整方法 在“多项微优化叠加后只看总时间，无法识别无效或有害改动”处拒绝",
  model: {
    primaryLabel: "逻辑",
    primaryUnit: "项",
    primaryInitial: 7,
    primaryMax: 39,
    primaryWeight: 2.2,
    secondaryLabel: "循环",
    secondaryUnit: "处",
    secondaryInitial: 3,
    secondaryMax: 19,
    secondaryWeight: 11,
    basePressure: 6,
    boundaryPenalty: 12,
    faultPenalty: 21,
    limit: 58,
    metricLabel: "数据压力",
  },
} as const;

export function Cc2e26CodeTuningTechniquesMechanismLab() {
  return <ConstructionMechanismLab {...profile} />;
}
