import { ConstructionMechanismLab } from "./construction-mechanism-lab";

const profile = {
  unitId: "cc2e-11-power-of-variable-names",
  title: "第11章：变量名的力量",
  nodes: ["领域概念", "语义命名", "规则一致", "作用域阅读", "维护判断"],
  concepts: [
    "第11章 变量名的力量",
    "11.1 选择好变量名的注意事项",
    "最重要的命名注意事项",
    "以问题为导向",
    "最适当的名字长度",
    "变量名字的效果范围",
    "变量名字中的计算值限定词",
    "变量名字中的常用反义词",
    "11.2 为特定类型的数据命名",
    "为循环索引命名",
    "为状态变量命名",
    "为临时变量命名",
    "为布尔变量命名",
    "为枚举类型命名",
    "为常量命名",
    "11.3 命名规则的力量",
    "为什么要有规则？",
    "何时采用命名规则",
    "正式程度",
    "11.4 非正式命名规则",
    "语言无关规则的指导原则",
    "语言相关规则的指导原则",
    "混合语言编程的注意事项",
    "命名规则示例",
    "11.5 标准前缀",
    "用户自定义类型缩写",
    "语义前缀",
    "标准前缀的优点",
    "11.6 创建具备可读性的短名称",
    "一般的缩写指导原则",
    "语音缩写",
    "有关缩写的评论",
    "11.7 应该避免的名称",
    "关键点",
  ],
  mechanism:
    "变量名编码问题域概念、单位和角色，长度随作用域调整，项目规则统一缩写并排除误导或过时名称",
  success: "第11章：变量名的力量 的机制链、结果和复位轨迹与预测一致",
  failure:
    "第11章：变量名的力量 在“名称描述历史实现而非当前含义，读者据此做出错误假设”处拒绝",
  model: {
    primaryLabel: "问题导向",
    primaryUnit: "项",
    primaryInitial: 10,
    primaryMax: 48,
    primaryWeight: 1.5,
    secondaryLabel: "长度",
    secondaryUnit: "处",
    secondaryInitial: 3,
    secondaryMax: 22,
    secondaryWeight: 8,
    basePressure: 9,
    boundaryPenalty: 15,
    faultPenalty: 18,
    limit: 60,
    metricLabel: "特定类型压力",
  },
} as const;

export function Cc2e11PowerOfVariableNamesMechanismLab() {
  return <ConstructionMechanismLab {...profile} />;
}
