import { ConstructionMechanismLab } from "./construction-mechanism-lab";

const profile = {
  unitId: "cc2e-28-managing-construction",
  title: "第28章：管理“构建”",
  nodes: ["实践标准", "配置基线", "估算跟踪", "人员环境", "管理反馈"],
  concepts: [
    "第28章 管理“构建”",
    "28.1 鼓励良好的编码实践",
    "设定标准的考虑事项",
    "鼓励良好的编码实践的技术",
    "本书的角色",
    "28.2 配置管理",
    "什么是配置管理？",
    "需求变更和设计变更",
    "软件代码变更",
    "工具版本",
    "机器配置",
    "备份计划",
    "有关配置管理的额外资源",
    "28.3 评估“构建”进度表",
    "评估的方法",
    "评估“构建”的工作量",
    "对进度的影响",
    "评估与控制",
    "如果你落后了该怎么办",
    "有关软件评估的额外资源",
    "28.4 度量",
    "有关软件度量的额外资源",
    "28.5 把程序员当人看",
    "程序员们怎样花费时间？",
    "性能差异与质量差异",
    "信仰问题",
    "物理环境",
    "有关“把程序员当人看”的额外资源",
    "28.6 管理你的管理者",
    "有关管理构造的额外资源",
    "相关标准",
    "关键点",
  ],
  mechanism:
    "构建管理通过编码标准、配置基线、工作分解、风险估算、度量和环境支持形成反馈，不用单一产出数字评价个人",
  success: "第28章：管理“构建” 的机制链、结果和复位轨迹与预测一致",
  failure:
    "第28章：管理“构建” 在“把代码行数或任务数作为个人绩效，诱导拆分和隐瞒质量问题”处拒绝",
  model: {
    primaryLabel: "编码实践",
    primaryUnit: "项",
    primaryInitial: 10,
    primaryMax: 48,
    primaryWeight: 1.7,
    secondaryLabel: "配置管理",
    secondaryUnit: "处",
    secondaryInitial: 3,
    secondaryMax: 22,
    secondaryWeight: 9,
    basePressure: 9,
    boundaryPenalty: 15,
    faultPenalty: 18,
    limit: 58,
    metricLabel: "进度估算压力",
  },
} as const;

export function Cc2e28ManagingConstructionMechanismLab() {
  return <ConstructionMechanismLab {...profile} />;
}
