import { ConstructionMechanismLab } from "./construction-mechanism-lab";

const profile = {
  unitId: "cc2e-22-developer-testing",
  title: "第22章：开发者测试",
  nodes: ["测试目标", "用例设计", "脚手架执行", "覆盖观察", "回归记录"],
  concepts: [
    "第22章 开发者测试",
    "22.1 开发者测试在软件质量中的角色",
    "构造中测试",
    "22.2 推荐的开发者测试方法",
    "先测试还是后测试",
    "开发者测试的局限性",
    "22.3 测试技巧锦囊",
    "不完整的测试",
    "结构化的基础测试",
    "数据流测试",
    "等价类划分",
    "猜测错误",
    "边界值分析",
    "几类坏数据",
    "几类好数据",
    "采用容易手工检查的测试用例",
    "22.4 典型错误",
    "哪些类包含最多的错误？",
    "错误的分类",
    "不完善的构造过程引发错误所占的比例",
    "你期望能发现多少错误",
    "测试本身的错误",
    "22.5 测试支持工具",
    "为测试各个类构造脚手架",
    "Diff工具",
    "测试数据生成器",
    "覆盖率监视器",
    "数据记录器/日志记录器",
    "符号调试工具",
    "系统干扰器",
    "错误数据库",
    "22.6 改善测试过程",
    "有计划的测试",
    "重新测试（回归测试）",
    "自动化测试",
    "22.7 保留测试记录",
    "个人测试记录",
    "推荐读物",
    "测试",
    "测试脚手架",
    "测试优先的开发",
    "相关标准",
    "关键点",
  ],
  mechanism:
    "开发者测试从需求和代码结构导出正常、边界、错误与独立路径用例，脚手架保证隔离、可重复和失败可诊断",
  success: "第22章：开发者测试 的机制链、结果和复位轨迹与预测一致",
  failure:
    "第22章：开发者测试 在“只写会通过的正常样例，或断言最终输出却不定位首差”处拒绝",
  model: {
    primaryLabel: "测试角色",
    primaryUnit: "项",
    primaryInitial: 8,
    primaryMax: 42,
    primaryWeight: 2,
    secondaryLabel: "测试优先",
    secondaryUnit: "处",
    secondaryInitial: 4,
    secondaryMax: 20,
    secondaryWeight: 10,
    basePressure: 7,
    boundaryPenalty: 13,
    faultPenalty: 22,
    limit: 56,
    metricLabel: "技巧压力",
  },
} as const;

export function Cc2e22DeveloperTestingMechanismLab() {
  return <ConstructionMechanismLab {...profile} />;
}
