import { ConstructionMechanismLab } from "./construction-mechanism-lab";

const profile = {
  unitId: "cc2e-05-design-in-construction",
  title: "第5章：软件构建中的设计",
  nodes: ["需求场景", "复杂度分解", "抽象边界", "设计试验", "代码验证"],
  concepts: [
    "第5章 软件构建中的设计",
    "5.1 设计中的挑战",
    "设计是一个险恶的问题",
    "设计是个了无章法的过程（即使它能得出清爽的成果）",
    "设计就是确定取舍和调整顺序的过程",
    "设计受到诸多限制",
    "设计是不确定的",
    "设计是一个启发式过程",
    "设计是自然而然形成的",
    "5.2 关键的设计概念",
    "软件的首要技术任务：管理复杂度",
    "理想的设计特征",
    "设计的层次",
    "5.3 设计构造块：启发式方法",
    "寻找现实世界中的对象",
    "形成一致的抽象",
    "封装实现细节",
    "当继承能简化设计时就继承",
    "隐藏秘密（信息隐藏）",
    "找出容易改变的区域",
    "保持松散耦合",
    "查阅常用的设计模式",
    "其他的启发式方法",
    "关于设计启发的总结",
    "使用启发式方法的原则",
    "5.4 设计实践",
    "迭代",
    "分而治之",
    "自上而下和自下而上的设计方法",
    "建立试验性原型",
    "合作设计",
    "要做多少设计才够？",
    "记录你的设计成果",
    "5.5 对流行的设计方法的评论",
    "更多资源",
    "软件设计，一般性问题",
    "软件设计理论",
    "设计模式",
    "广义的设计",
    "标准",
    "关键点",
  ],
  mechanism:
    "构建设计把复杂场景分解为职责、抽象层、接口和数据所有权，并用最小代码实验迭代验证高风险决定",
  success: "第5章：软件构建中的设计 的机制链、结果和复位轨迹与预测一致",
  failure:
    "第5章：软件构建中的设计 在“一次画完全部设计且没有可运行反馈，错误抽象被大规模复制”处拒绝",
  model: {
    primaryLabel: "设计挑战",
    primaryUnit: "项",
    primaryInitial: 8,
    primaryMax: 42,
    primaryWeight: 1.8,
    secondaryLabel: "层次",
    secondaryUnit: "处",
    secondaryInitial: 4,
    secondaryMax: 20,
    secondaryWeight: 8,
    basePressure: 7,
    boundaryPenalty: 13,
    faultPenalty: 16,
    limit: 62,
    metricLabel: "启发式压力",
  },
} as const;

export function Cc2e05DesignInConstructionMechanismLab() {
  return <ConstructionMechanismLab {...profile} />;
}
