// Generated by scripts/generate-chapter-component-registry.mjs.
// MDX imports are declarations only; next-mdx-remote removes them at runtime.
import type { MDXRemoteProps } from "next-mdx-remote/rsc";

type ChapterMdxComponents = NonNullable<MDXRemoteProps["components"]>;
type ChapterComponentLoader = () => Promise<ChapterMdxComponents>;

const chapterComponentLoaders: Record<string, ChapterComponentLoader> = {
  "algorithms-4e/04-graphs/directed-graphs": async () => {
    const module0 =
      await import("@/components/mdx/algorithms-4e/diagrams/directed-graphs");
    return {
      Algs4DirectedGraphModelMap: module0.Algs4DirectedGraphModelMap,
    } as ChapterMdxComponents;
  },
  "algorithms-4e/04-graphs/minimum-spanning-trees": async () => {
    const module0 =
      await import("@/components/mdx/algorithms-4e/diagrams/minimum-spanning-trees");
    return {
      Algs4WeightedGraphModelMap: module0.Algs4WeightedGraphModelMap,
    } as ChapterMdxComponents;
  },
  "algorithms-4e/04-graphs/shortest-paths": async () => {
    const module0 =
      await import("@/components/mdx/algorithms-4e/diagrams/shortest-paths");
    return {
      Algs4WeightedDigraphModelMap: module0.Algs4WeightedDigraphModelMap,
    } as ChapterMdxComponents;
  },
  "algorithms-4e/04-graphs/undirected-graphs": async () => {
    const module0 =
      await import("@/components/mdx/algorithms-4e/diagrams/undirected-graphs");
    return {
      Algs4UndirectedGraphModelMap: module0.Algs4UndirectedGraphModelMap,
      Algs4DfsApplicationMap: module0.Algs4DfsApplicationMap,
    } as ChapterMdxComponents;
  },
  "algorithms-4e/06-context/reductions": async () => {
    const module0 =
      await import("@/components/mdx/algorithms-4e/diagrams/reductions");
    return {
      Algs4ReductionMap: module0.Algs4ReductionMap,
    } as ChapterMdxComponents;
  },
  "android-design-patterns/00-official-learning-map/adp-official-learning-map":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-official-learning-map"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        AdpOfficialLearningMapLab: modules[0].AdpOfficialLearningMapLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/01-preface/adp-preface": async () => {
    const modules = await Promise.all([
      import("@/components/mdx/android-design-patterns/adp-preface"),
      import("@/components/mdx/android-design-patterns/android-architecture-lab"),
    ]);
    return {
      AdpPrefaceLab: modules[0].AdpPrefaceLab,
      AndroidDecisionMap: modules[1].AndroidDecisionMap,
      AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
    } as ChapterMdxComponents;
  },
  "android-design-patterns/02-chapter-01/adp-01-android-app-basic-structure":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-01-android-app-basic-structure"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp01AndroidAppBasicStructureLab:
          modules[0].Adp01AndroidAppBasicStructureLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/03-chapter-02/adp-02-mvvm-application-structure":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-02-mvvm-application-structure"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp02MvvmApplicationStructureLab:
          modules[0].Adp02MvvmApplicationStructureLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/04-chapter-03/adp-03-mvp-application-structure":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-03-mvp-application-structure"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp03MvpApplicationStructureLab:
          modules[0].Adp03MvpApplicationStructureLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/05-chapter-04/adp-04-incremental-development-design":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-04-incremental-development-design"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp04IncrementalDevelopmentDesignLab:
          modules[0].Adp04IncrementalDevelopmentDesignLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/06-chapter-05/adp-05-designer-role-in-oss":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-05-designer-role-in-oss"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp05DesignerRoleInOssLab: modules[0].Adp05DesignerRoleInOssLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/07-chapter-06/adp-06-flux-architecture":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-06-flux-architecture"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp06FluxArchitectureLab: modules[0].Adp06FluxArchitectureLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/08-chapter-07/adp-07-team-and-architecture":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-07-team-and-architecture"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp07TeamAndArchitectureLab: modules[0].Adp07TeamAndArchitectureLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/09-chapter-08/adp-08-android-architecture-components":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-08-android-architecture-components"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        Adp08AndroidArchitectureComponentsLab:
          modules[0].Adp08AndroidArchitectureComponentsLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/10-afterword/adp-afterword": async () => {
    const modules = await Promise.all([
      import("@/components/mdx/android-design-patterns/adp-afterword"),
      import("@/components/mdx/android-design-patterns/android-architecture-lab"),
    ]);
    return {
      AdpAfterwordLab: modules[0].AdpAfterwordLab,
      AndroidDecisionMap: modules[1].AndroidDecisionMap,
      AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
    } as ChapterMdxComponents;
  },
  "android-design-patterns/11-index/adp-index": async () => {
    const modules = await Promise.all([
      import("@/components/mdx/android-design-patterns/adp-index"),
      import("@/components/mdx/android-design-patterns/android-architecture-lab"),
    ]);
    return {
      AdpIndexLab: modules[0].AdpIndexLab,
      AndroidDecisionMap: modules[1].AndroidDecisionMap,
      AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
    } as ChapterMdxComponents;
  },
  "android-design-patterns/12-author-profiles/adp-author-profiles":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-author-profiles"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        AdpAuthorProfilesLab: modules[0].AdpAuthorProfilesLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "android-design-patterns/13-official-final-review/adp-official-final-review":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/android-design-patterns/adp-official-final-review"),
        import("@/components/mdx/android-design-patterns/android-architecture-lab"),
      ]);
      return {
        AdpOfficialFinalReviewLab: modules[0].AdpOfficialFinalReviewLab,
        AndroidDecisionMap: modules[1].AndroidDecisionMap,
        AndroidFailureTimeline: modules[1].AndroidFailureTimeline,
      } as ChapterMdxComponents;
    },
  "auto-why-car-runs/00-learning-map/learning-map": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/learning-map");
    return {
      AutoLearningMapLab: module0.AutoLearningMapLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/01-whole-car/whole-car-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/whole-car-system");
    return {
      WholeCarSystemsLab: module0.WholeCarSystemsLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/02-body/body-structure": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/body-structure");
    return {
      BodyStructureLab: module0.BodyStructureLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/03-engine/engine-principles": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/engine-principles");
    return {
      EnginePrinciplesLab: module0.EnginePrinciplesLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/04-transmission/transmission-principles": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/transmission-principles");
    return {
      TransmissionLab: module0.TransmissionLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/05-drivetrain/drivetrain-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/drivetrain-system");
    return {
      DrivetrainLab: module0.DrivetrainLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/06-suspension/suspension-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/suspension-system");
    return {
      SuspensionLab: module0.SuspensionLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/07-steering/steering-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/steering-system");
    return {
      SteeringLab: module0.SteeringLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/08-brake/brake-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/brake-system");
    return {
      BrakeLab: module0.BrakeLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/09-electronics/electronics-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/electronics-system");
    return {
      ElectronicsLab: module0.ElectronicsLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/10-tires/tire-wheel-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/tire-wheel-system");
    return {
      TireLab: module0.TireLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/11-electric-drive/electric-drive-system": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/electric-drive-system");
    return {
      ElectricDriveLab: module0.ElectricDriveLab,
    } as ChapterMdxComponents;
  },
  "auto-why-car-runs/12-design-manufacturing/design-manufacturing":
    async () => {
      const module0 =
        await import("@/components/mdx/auto-why-car-runs/labs/design-manufacturing");
      return {
        ManufacturingLab: module0.ManufacturingLab,
      } as ChapterMdxComponents;
    },
  "auto-why-car-runs/13-final-review/final-review": async () => {
    const module0 =
      await import("@/components/mdx/auto-why-car-runs/labs/final-review");
    return {
      AutoFinalReviewLab: module0.AutoFinalReviewLab,
    } as ChapterMdxComponents;
  },
  "coding-interviews/00-interview-process/interview-process": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/interview-process");
    return {
      InterviewFormatMap: module0.InterviewFormatMap,
      InterviewRoundDiagram: module0.InterviewRoundDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/01-basics/assignment-operator": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/assignment-operator");
    return {
      AssignmentContractMap: module0.AssignmentContractMap,
      OwnershipTransitionDiagram: module0.OwnershipTransitionDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/01-basics/duplicate-in-array-no-edit": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/duplicate-in-array-no-edit");
    return {
      ValueRangeDiagram: module0.ValueRangeDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/01-basics/duplicate-in-array": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/duplicate-in-array");
    return {
      PlacementInvariantDiagram: module0.PlacementInvariantDiagram,
      ContractMatrixMap: module0.ContractMatrixMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/01-basics/singleton": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/singleton");
    return {
      SingletonBoundaryMap: module0.SingletonBoundaryMap,
      ConcurrencyRaceDiagram: module0.ConcurrencyRaceDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/accumulate": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/accumulate");
    return {
      AccumulateConstraintDiagram: module0.AccumulateConstraintDiagram,
      AccumulateDispatchMap: module0.AccumulateDispatchMap,
      AccumulateTemplateDiagram: module0.AccumulateTemplateDiagram,
      AccumulateRecursionDiagram: module0.AccumulateRecursionDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/continous-cards": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/continous-cards");
    return {
      ContinuousCardsSortDiagram: module0.ContinuousCardsSortDiagram,
      ContinuousCardsJokerBudgetMap: module0.ContinuousCardsJokerBudgetMap,
      ContinuousCardsContractDiagram: module0.ContinuousCardsContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/continuous-sequence-with-sum": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/continuous-sequence-with-sum");
    return {
      ContinuousSequenceWindowDiagram: module0.ContinuousSequenceWindowDiagram,
      ContinuousSequenceMovementMap: module0.ContinuousSequenceMovementMap,
      ContinuousSequenceContractDiagram:
        module0.ContinuousSequenceContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/greatest-sum-of-subarrays": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/greatest-sum-of-subarrays");
    return {
      GreatestSumRecurrenceDiagram: module0.GreatestSumRecurrenceDiagram,
      GreatestSumAllNegativeDiagram: module0.GreatestSumAllNegativeDiagram,
      GreatestSumContractDiagram: module0.GreatestSumContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/inverse-pairs": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/inverse-pairs");
    return {
      InversePairDecompositionDiagram: module0.InversePairDecompositionDiagram,
      InversePairBufferSwapMap: module0.InversePairBufferSwapMap,
      InversePairContractDiagram: module0.InversePairContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/k-least-numbers": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/k-least-numbers");
    return {
      KLeastPartitionDiagram: module0.KLeastPartitionDiagram,
      KLeastTradeoffDiagram: module0.KLeastTradeoffDiagram,
      KLeastOutputContractDiagram: module0.KLeastOutputContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/matrix-path": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/matrix-path");
    return {
      MatrixPathBoardDiagram: module0.MatrixPathBoardDiagram,
      BacktrackingStateMap: module0.BacktrackingStateMap,
      VisitedRollbackDiagram: module0.VisitedRollbackDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/maximal-profit": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/maximal-profit");
    return {
      MaximalProfitTimelineDiagram: module0.MaximalProfitTimelineDiagram,
      MaximalProfitInvariantMap: module0.MaximalProfitInvariantMap,
      MaximalProfitContractDiagram: module0.MaximalProfitContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/min-rotated-array": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/min-rotated-array");
    return {
      RotatedArrayStructureDiagram: module0.RotatedArrayStructureDiagram,
      RotatedSearchInvariantMap: module0.RotatedSearchInvariantMap,
      DuplicateRotationAmbiguityDiagram:
        module0.DuplicateRotationAmbiguityDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/more-than-half-number": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/more-than-half-number");
    return {
      MajorityPartitionDiagram: module0.MajorityPartitionDiagram,
      MajorityCancellationMap: module0.MajorityCancellationMap,
      MajorityVerificationDiagram: module0.MajorityVerificationDiagram,
      MajorityInputContractDiagram: module0.MajorityInputContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/number-of-k": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/number-of-k");
    return {
      NumberOfKSortedRunDiagram: module0.NumberOfKSortedRunDiagram,
      NumberOfKContractDiagram: module0.NumberOfKContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/reorder-array": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/reorder-array");
    return {
      OddEvenPartitionDiagram: module0.OddEvenPartitionDiagram,
      PartitionInvariantMap: module0.PartitionInvariantMap,
      PredicateExtensionDiagram: module0.PredicateExtensionDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/spiral-matrix": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/spiral-matrix");
    return {
      SpiralRingPathDiagram: module0.SpiralRingPathDiagram,
      SpiralEdgeConditionMap: module0.SpiralEdgeConditionMap,
      SpiralStartInvariantDiagram: module0.SpiralStartInvariantDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/arrays/two-numbers-with-sum": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/two-numbers-with-sum");
    return {
      TwoNumbersWithSumPointerDiagram: module0.TwoNumbersWithSumPointerDiagram,
      TwoNumbersWithSumEliminationMap: module0.TwoNumbersWithSumEliminationMap,
      TwoNumbersWithSumContractDiagram:
        module0.TwoNumbersWithSumContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/copy-complex-list": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/copy-complex-list");
    return {
      ComplexListInterleaveDiagram: module0.ComplexListInterleaveDiagram,
      ComplexSiblingMappingMap: module0.ComplexSiblingMappingMap,
      ComplexListSplitDiagram: module0.ComplexListSplitDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/delete-duplicated-node": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/delete-duplicated-node");
    return {
      DuplicateRunDeletionDiagram: module0.DuplicateRunDeletionDiagram,
      DuplicatePredecessorInvariantMap:
        module0.DuplicatePredecessorInvariantMap,
      HeadRunRewireDiagram: module0.HeadRunRewireDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/delete-node": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/delete-node");
    return {
      SuccessorCopyDeleteDiagram: module0.SuccessorCopyDeleteDiagram,
      DeleteNodeCaseMap: module0.DeleteNodeCaseMap,
      NodeIdentityImpactDiagram: module0.NodeIdentityImpactDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/entry-node-of-loop": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/entry-node-of-loop");
    return {
      LoopMeetingDiagram: module0.LoopMeetingDiagram,
      LoopLengthCountingMap: module0.LoopLengthCountingMap,
      LoopGapEntryDiagram: module0.LoopGapEntryDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/first-common-nodes-in-lists": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/first-common-nodes-in-lists");
    return {
      ListIntersectionIdentityDiagram: module0.ListIntersectionIdentityDiagram,
      SharedSuffixProofMap: module0.SharedSuffixProofMap,
      ListIntersectionContractDiagram: module0.ListIntersectionContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/kth-node-from-end": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/kth-node-from-end");
    return {
      KthGapDiagram: module0.KthGapDiagram,
      KthPointerInvariantMap: module0.KthPointerInvariantMap,
      KthBoundaryDiagram: module0.KthBoundaryDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/merge-sorted-lists": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/merge-sorted-lists");
    return {
      MergeHeadChoiceDiagram: module0.MergeHeadChoiceDiagram,
      MergeRecursionInvariantMap: module0.MergeRecursionInvariantMap,
      MergeTiePolicyDiagram: module0.MergeTiePolicyDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/print-list-reverse": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/print-list-reverse");
    return {
      LinkedListDirectionDiagram: module0.LinkedListDirectionDiagram,
      OutputContractMap: module0.OutputContractMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/linked-lists/reverse-list": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/reverse-list");
    return {
      ReversePointerOrderDiagram: module0.ReversePointerOrderDiagram,
      ReverseInvariantMap: module0.ReverseInvariantMap,
      ReverseHeadTailDiagram: module0.ReverseHeadTailDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/cutting-rope": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/cutting-rope");
    return {
      RopePartitionDiagram: module0.RopePartitionDiagram,
      RopeDpStateMap: module0.RopeDpStateMap,
      GreedyRemainderDiagram: module0.GreedyRemainderDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/dices-probability": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/dices-probability");
    return {
      DicesProbabilityStateDiagram: module0.DicesProbabilityStateDiagram,
      DicesProbabilityDistributionChart:
        module0.DicesProbabilityDistributionChart,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/last-number-in-circle": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/last-number-in-circle");
    return {
      LastNumberCircleDiagram: module0.LastNumberCircleDiagram,
      LastNumberRelabelMap: module0.LastNumberRelabelMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/number-of-1-bits": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/number-of-1-bits");
    return {
      BitMaskSweepDiagram: module0.BitMaskSweepDiagram,
      ClearLowestOneDiagram: module0.ClearLowestOneDiagram,
      BitCountMethodMap: module0.BitCountMethodMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/number-of-1": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/number-of-1");
    return {
      NumberOf1RecursiveDecompositionDiagram:
        module0.NumberOf1RecursiveDecompositionDiagram,
      NumberOf1HighestDigitDiagram: module0.NumberOf1HighestDigitDiagram,
      NumberOf1ComplexityDiagram: module0.NumberOf1ComplexityDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/power": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/power");
    return {
      ExponentHalvingDiagram: module0.ExponentHalvingDiagram,
      BinaryExponentStateMap: module0.BinaryExponentStateMap,
      PowerContractMap: module0.PowerContractMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/math/ugly-number": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/ugly-number");
    return {
      UglyFactorizationDiagram: module0.UglyFactorizationDiagram,
      UglyThreeStreamMap: module0.UglyThreeStreamMap,
      UglyApproachComparisonDiagram: module0.UglyApproachComparisonDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/recursion/fibonacci": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/fibonacci");
    return {
      FibonacciRecursionOverlapDiagram:
        module0.FibonacciRecursionOverlapDiagram,
      FibonacciRollingStateMap: module0.FibonacciRollingStateMap,
      FrogStepCorrespondenceDiagram: module0.FrogStepCorrespondenceDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/recursion/print-numbers": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/print-numbers");
    return {
      DecimalIncrementDiagram: module0.DecimalIncrementDiagram,
      CarryTransitionMap: module0.CarryTransitionMap,
      DigitEnumerationTreeDiagram: module0.DigitEnumerationTreeDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/stacks-queues/max-in-sliding-window": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/max-in-sliding-window");
    return {
      MaxSlidingWindowCandidateDiagram:
        module0.MaxSlidingWindowCandidateDiagram,
      MaxSlidingWindowExpiryMap: module0.MaxSlidingWindowExpiryMap,
      MaxSlidingWindowContractDiagram: module0.MaxSlidingWindowContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/stacks-queues/min-stack": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/min-stack");
    return {
      MinStackSnapshotDiagram: module0.MinStackSnapshotDiagram,
      MinStackInvariantMap: module0.MinStackInvariantMap,
      MinStackOperationMap: module0.MinStackOperationMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/stacks-queues/queue-with-two-stacks": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/queue-with-two-stacks");
    return {
      TwoStackQueueFlowDiagram: module0.TwoStackQueueFlowDiagram,
      QueueStateInvariantMap: module0.QueueStateInvariantMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/stacks-queues/stack-push-pop-order": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/stack-push-pop-order");
    return {
      StackSequenceSimulationDiagram: module0.StackSequenceSimulationDiagram,
      StackTargetDecisionMap: module0.StackTargetDecisionMap,
      StackSequenceCounterexampleDiagram:
        module0.StackSequenceCounterexampleDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/stacks-queues/stream-median": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/stream-median");
    return {
      StreamMedianHeapInvariantDiagram:
        module0.StreamMedianHeapInvariantDiagram,
      StreamMedianRoutingDiagram: module0.StreamMedianRoutingDiagram,
      StreamMedianContractDiagram: module0.StreamMedianContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/first-character-in-stream": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/first-character-in-stream");
    return {
      OccurrenceSentinelDiagram: module0.OccurrenceSentinelDiagram,
      FirstPositionScanMap: module0.FirstPositionScanMap,
      StaticAndStreamUniqueDiagram: module0.StaticAndStreamUniqueDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/first-not-repeating-char": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/first-not-repeating-char");
    return {
      FirstUniqueFrequencyDiagram: module0.FirstUniqueFrequencyDiagram,
      FirstUniqueOrderMap: module0.FirstUniqueOrderMap,
      FirstUniqueContractDiagram: module0.FirstUniqueContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/left-rotate-string": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/left-rotate-string");
    return {
      LeftRotatePartitionDiagram: module0.LeftRotatePartitionDiagram,
      LeftRotateContractMap: module0.LeftRotateContractMap,
      LeftRotateProofDiagram: module0.LeftRotateProofDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/longest-substring-without-dup": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/longest-substring-without-dup");
    return {
      DuplicateDecisionDiagram: module0.DuplicateDecisionDiagram,
      BruteForceSearchMap: module0.BruteForceSearchMap,
      LowercaseAlphabetContractDiagram:
        module0.LowercaseAlphabetContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/numeric-strings": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/numeric-strings");
    return {
      NumericGrammarDiagram: module0.NumericGrammarDiagram,
      NumericCursorInvariantMap: module0.NumericCursorInvariantMap,
      DecimalExponentFlowDiagram: module0.DecimalExponentFlowDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/regular-expressions-matching": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/regular-expressions-matching");
    return {
      RegexTokenSemanticsDiagram: module0.RegexTokenSemanticsDiagram,
      StarBranchDecisionMap: module0.StarBranchDecisionMap,
      RegexStateProgressDiagram: module0.RegexStateProgressDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/replace-spaces": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/replace-spaces");
    return {
      ExpansionLayoutDiagram: module0.ExpansionLayoutDiagram,
      CapacityFormulaMap: module0.CapacityFormulaMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/reverse-words-in-sentence": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/reverse-words-in-sentence");
    return {
      ReverseWordsTwoPassDiagram: module0.ReverseWordsTwoPassDiagram,
      ReverseWordsSpaceMap: module0.ReverseWordsSpaceMap,
      ReverseWordsInvariantDiagram: module0.ReverseWordsInvariantDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/sort-array-for-min-number": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/sort-array-for-min-number");
    return {
      MinNumberSortDiagram: module0.MinNumberSortDiagram,
      MinNumberExchangeProofDiagram: module0.MinNumberExchangeProofDiagram,
      MinNumberMemoryContractDiagram: module0.MinNumberMemoryContractDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/string-permutation": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/string-permutation");
    return {
      PermutationSwapTreeDiagram: module0.PermutationSwapTreeDiagram,
      PermutationSwapBackMap: module0.PermutationSwapBackMap,
      PermutationDuplicatePolicyDiagram:
        module0.PermutationDuplicatePolicyDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/strings/string-to-int": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/string-to-int");
    return {
      StringToIntContractDiagram: module0.StringToIntContractDiagram,
      StringToIntBoundaryMap: module0.StringToIntBoundaryMap,
      StringToIntValidityDiagram: module0.StringToIntValidityDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/balanced-binary-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/balanced-binary-tree");
    return {
      BalancedBinaryTreeLocalRuleDiagram:
        module0.BalancedBinaryTreeLocalRuleDiagram,
      BalancedBinaryTreeWorkDiagram: module0.BalancedBinaryTreeWorkDiagram,
      BalancedBinaryTreeContractMap: module0.BalancedBinaryTreeContractMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/common-parent-in-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/common-parent-in-tree");
    return {
      CommonParentDecisionMap: module0.CommonParentDecisionMap,
      CommonParentTreeDiagram: module0.CommonParentTreeDiagram,
      CommonParentConventionDiagram: module0.CommonParentConventionDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/convert-binary-search-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/convert-binary-search-tree");
    return {
      BstInorderLinkDiagram: module0.BstInorderLinkDiagram,
      BstNodeLinkInvariantMap: module0.BstNodeLinkInvariantMap,
      BstLinearBoundaryDiagram: module0.BstLinearBoundaryDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/kth-node-in-bst": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/kth-node-in-bst");
    return {
      KthNodeBstOrderDiagram: module0.KthNodeBstOrderDiagram,
      KthNodeCounterFlowDiagram: module0.KthNodeCounterFlowDiagram,
      KthNodeContractMap: module0.KthNodeContractMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/mirror-binary-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/mirror-binary-tree");
    return {
      MirrorSwapDiagram: module0.MirrorSwapDiagram,
      MirrorTraversalMap: module0.MirrorTraversalMap,
      MirrorSourceGuardDiagram: module0.MirrorSourceGuardDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/next-node-in-binary-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/next-node-in-binary-tree");
    return {
      InorderSuccessorCaseMap: module0.InorderSuccessorCaseMap,
      AncestorClimbDiagram: module0.AncestorClimbDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/path-in-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/path-in-tree");
    return {
      RootLeafPathDiagram: module0.RootLeafPathDiagram,
      PathBacktrackStateMap: module0.PathBacktrackStateMap,
      RootLeafConditionMap: module0.RootLeafConditionMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/print-tree-from-top-to-bottom": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/print-tree-from-top-to-bottom");
    return {
      LevelOrderQueueDiagram: module0.LevelOrderQueueDiagram,
      FifoLayerInvariantMap: module0.FifoLayerInvariantMap,
      LevelOrderWidthDiagram: module0.LevelOrderWidthDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/print-trees-in-lines": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/print-trees-in-lines");
    return {
      TreeLineCounterDiagram: module0.TreeLineCounterDiagram,
      TreeLineBoundaryMap: module0.TreeLineBoundaryMap,
      TreeLineStrategyMap: module0.TreeLineStrategyMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/print-trees-in-zigzag": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/print-trees-in-zigzag");
    return {
      ZigzagTwoStackDiagram: module0.ZigzagTwoStackDiagram,
      ZigzagChildPushOrderMap: module0.ZigzagChildPushOrderMap,
      ZigzagStackSwapDiagram: module0.ZigzagStackSwapDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/rebuild-binary-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/rebuild-binary-tree");
    return {
      TraversalSplitDiagram: module0.TraversalSplitDiagram,
      IntervalInvariantMap: module0.IntervalInvariantMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/serialize-binary-trees": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/serialize-binary-trees");
    return {
      TreeSerializationTokenDiagram: module0.TreeSerializationTokenDiagram,
      NullMarkerAmbiguityMap: module0.NullMarkerAmbiguityMap,
      DeserializeCursorMap: module0.DeserializeCursorMap,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/squence-of-bst": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/squence-of-bst");
    return {
      BstPostorderPartitionDiagram: module0.BstPostorderPartitionDiagram,
      BstPostorderRecursionMap: module0.BstPostorderRecursionMap,
      BstPostorderFailureDiagram: module0.BstPostorderFailureDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/subtree-structure": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/subtree-structure");
    return {
      SubtreeCandidateSearchDiagram: module0.SubtreeCandidateSearchDiagram,
      SubtreeMatchBoundaryMap: module0.SubtreeMatchBoundaryMap,
      SubstructureVsSubtreeDiagram: module0.SubstructureVsSubtreeDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/symmetric-binary-tree": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/symmetric-binary-tree");
    return {
      SymmetricTraversalDiagram: module0.SymmetricTraversalDiagram,
      MirrorPairBoundaryMap: module0.MirrorPairBoundaryMap,
      SymmetricShapeCounterexampleDiagram:
        module0.SymmetricShapeCounterexampleDiagram,
    } as ChapterMdxComponents;
  },
  "coding-interviews/trees/tree-depth": async () => {
    const module0 =
      await import("@/components/mdx/coding-interviews/diagrams/tree-depth");
    return {
      TreeDepthPathDiagram: module0.TreeDepthPathDiagram,
      TreeDepthCallStackDiagram: module0.TreeDepthCallStackDiagram,
      TreeDepthContractMap: module0.TreeDepthContractMap,
    } as ChapterMdxComponents;
  },
  "competitive-algorithms/00-foundations/01-welcome-to-algorithms":
    async () => {
      const module0 =
        await import("@/components/mdx/competitive-algorithms/diagrams/01-welcome-to-algorithms");
      return {
        CAIContestLoopMap: module0.CAIContestLoopMap,
        CAIBottleneckMap: module0.CAIBottleneckMap,
      } as ChapterMdxComponents;
    },
  "cpp-high-performance/03-official/measuring-performance": async () => {
    const module0 =
      await import("@/components/mdx/cpp-high-performance/diagrams/measuring-performance");
    return {
      ChpComplexityScaleMap: module0.ChpComplexityScaleMap,
      ChpMeasurementProtocolMap: module0.ChpMeasurementProtocolMap,
      ChpProfilerEvidenceMap: module0.ChpProfilerEvidenceMap,
    } as ChapterMdxComponents;
  },
  "cpp-primer-5e/cpp-class-design/overloaded-operations": async () => {
    const module0 =
      await import("@/components/mdx/cpp-primer-5e/diagrams/overloaded-operations");
    return {
      CppOperatorAndConversionContractDiagram:
        module0.CppOperatorAndConversionContractDiagram,
    } as ChapterMdxComponents;
  },
  "cpp-primer-plus/03-official/dealing-with-data": async () => {
    const module0 =
      await import("@/components/mdx/cpp-primer-plus/diagrams/dealing-with-data");
    return {
      EppDataConversionFlow: module0.EppDataConversionFlow,
      EppDataRepresentationMap: module0.EppDataRepresentationMap,
    } as ChapterMdxComponents;
  },
  "cpp-primer-plus/09-official/memory-models-and-namespaces": async () => {
    const module0 =
      await import("@/components/mdx/cpp-primer-plus/diagrams/memory-models-and-namespaces");
    return {
      EppStorageScopeLinkageFlow: module0.EppStorageScopeLinkageFlow,
      EppTranslationUnitBuildMap: module0.EppTranslationUnitBuildMap,
    } as ChapterMdxComponents;
  },
  "cpp-primer-plus/15-official/friends-exceptions-and-more": async () => {
    const module0 =
      await import("@/components/mdx/cpp-primer-plus/diagrams/friends-exceptions-and-more");
    return {
      EppExceptionUnwindFlow: module0.EppExceptionUnwindFlow,
      EppFriendAccessMap: module0.EppFriendAccessMap,
    } as ChapterMdxComponents;
  },
  "cpp-primer-plus/18-official/visiting-new-cpp-standard": async () => {
    const module0 =
      await import("@/components/mdx/cpp-primer-plus/diagrams/visiting-new-cpp-standard");
    return {
      EppModernFeatureMap: module0.EppModernFeatureMap,
      EppMoveStateFlow: module0.EppMoveStateFlow,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/00-intro/learning-map": async () => {
    const module0 = await import("@/components/mdx/cpu-eye-cpp/learning-map");
    return {
      CpuLearningMapLab: module0.CpuLearningMapLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/01-prerequisites/prerequisites": async () => {
    const module0 = await import("@/components/mdx/cpu-eye-cpp/prerequisites");
    return {
      CpuPrerequisitesLab: module0.CpuPrerequisitesLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/02-basic-syntax/basic-syntax": async () => {
    const module0 =
      await import("@/components/mdx/cpu-eye-cpp/diagrams/basic-syntax");
    return {
      CpuEyeBranchControlFlowMap: module0.CpuEyeBranchControlFlowMap,
      CpuEyeIncrementConversionCostMap:
        module0.CpuEyeIncrementConversionCostMap,
      CpuEyePointerArrayAddressMap: module0.CpuEyePointerArrayAddressMap,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/03-function-principles/function-principles": async () => {
    const module0 =
      await import("@/components/mdx/cpu-eye-cpp/function-principles");
    return {
      CpuFunctionPrinciplesLab: module0.CpuFunctionPrinciplesLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/04-cpp-features/cpp-features": async () => {
    const module0 = await import("@/components/mdx/cpu-eye-cpp/cpp-features");
    return {
      CpuCppFeaturesLab: module0.CpuCppFeaturesLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/05-advanced-programming/advanced-programming": async () => {
    const module0 =
      await import("@/components/mdx/cpu-eye-cpp/advanced-programming");
    return {
      CpuAdvancedProgrammingLab: module0.CpuAdvancedProgrammingLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/06-interview-challenges/interview-challenges": async () => {
    const module0 =
      await import("@/components/mdx/cpu-eye-cpp/interview-challenges");
    return {
      CpuInterviewChallengesLab: module0.CpuInterviewChallengesLab,
    } as ChapterMdxComponents;
  },
  "cpu-eye-cpp/07-review/final-review": async () => {
    const module0 = await import("@/components/mdx/cpu-eye-cpp/final-review");
    return {
      CpuFinalReviewLab: module0.CpuFinalReviewLab,
    } as ChapterMdxComponents;
  },
  "deep-opengl/00-fundamentals/dog-learning-map": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-learning-map");
    return {
      DogApiBaselineDiagram: module0.DogApiBaselineDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/01-core/dog-opengl-architecture": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-opengl-architecture");
    return {
      DogStateCaptureDiagram: module0.DogStateCaptureDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/01-core/dog-shader-language": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-shader-language");
    return {
      DogShaderInterfaceDiagram: module0.DogShaderInterfaceDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/01-core/dog-webgl-basics": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-webgl-basics");
    return {
      DogCanvasSizeDiagram: module0.DogCanvasSizeDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/02-advanced/dog-cross-platform": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-cross-platform");
    return {
      DogCapabilityContractDiagram: module0.DogCapabilityContractDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/02-advanced/dog-fbo-techniques": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-fbo-techniques");
    return {
      DogFboCompletenessDiagram: module0.DogFboCompletenessDiagram,
    } as ChapterMdxComponents;
  },
  "deep-opengl/02-advanced/dog-rendering-optimization": async () => {
    const module0 =
      await import("@/components/mdx/deep-opengl/diagrams/dog-rendering-optimization");
    return {
      DogBottleneckDecisionDiagram: module0.DogBottleneckDecisionDiagram,
    } as ChapterMdxComponents;
  },
  "dsa-cpp/01-linear-structures/lists-stacks-queues": async () => {
    const module0 =
      await import("@/components/mdx/dsa-cpp/diagrams/lists-stacks-queues");
    return {
      DsaAdtBoundaryDiagram: module0.DsaAdtBoundaryDiagram,
    } as ChapterMdxComponents;
  },
  "effective-cpp/02-resource-management/item-15-raw-resource-access":
    async () => {
      const module0 =
        await import("@/components/mdx/effective-cpp/diagrams/item-15-raw-resource-access");
      return {
        EcppBorrowLifetimeMap: module0.EcppBorrowLifetimeMap,
        EcppRawAccessBoundaryMap: module0.EcppRawAccessBoundaryMap,
        EcppResourceAccessFormsMap: module0.EcppResourceAccessFormsMap,
      } as ChapterMdxComponents;
    },
  "effective-cpp/03-designs-declarations/item-24-non-member-conversions":
    async () => {
      const module0 =
        await import("@/components/mdx/effective-cpp/diagrams/item-24-non-member-conversions");
      return {
        EcppConversionPolicyDecisionMap:
          module0.EcppConversionPolicyDecisionMap,
        EcppMemberConversionAsymmetryMap:
          module0.EcppMemberConversionAsymmetryMap,
        EcppNonMemberCandidateFlowMap: module0.EcppNonMemberCandidateFlowMap,
      } as ChapterMdxComponents;
    },
  "effective-cpp/04-implementations/item-27-minimize-casting": async () => {
    const module0 =
      await import("@/components/mdx/effective-cpp/diagrams/item-27-minimize-casting");
    return {
      EcppBaseSubobjectAdjustmentMap: module0.EcppBaseSubobjectAdjustmentMap,
      EcppCastFreeDispatchDecisionMap: module0.EcppCastFreeDispatchDecisionMap,
      EcppCastTaxonomyRiskMap: module0.EcppCastTaxonomyRiskMap,
    } as ChapterMdxComponents;
  },
  "effective-cpp/08-miscellaneous/item-53-compiler-warnings": async () => {
    const module0 =
      await import("@/components/mdx/effective-cpp/diagrams/item-53-compiler-warnings");
    return {
      EcppHiddenVirtualWarningMap: module0.EcppHiddenVirtualWarningMap,
      EcppMultiCompilerWarningMap: module0.EcppMultiCompilerWarningMap,
      EcppWarningLifecycleMap: module0.EcppWarningLifecycleMap,
    } as ChapterMdxComponents;
  },
  "effective-modern-cpp/00-intro/learning-map": async () => {
    const module0 =
      await import("@/components/mdx/effective-modern-cpp/diagrams/learning-map");
    return {
      EmcppEightChapterJourneyMap: module0.EmcppEightChapterJourneyMap,
      EmcppItemEvidenceMap: module0.EmcppItemEvidenceMap,
      EmcppPrincipleDependencyFlowMap: module0.EmcppPrincipleDependencyFlowMap,
    } as ChapterMdxComponents;
  },
  "effective-modern-cpp/02-moving-to-modern-cpp/item-07-parentheses-vs-braces":
    async () => {
      const module0 =
        await import("@/components/mdx/effective-modern-cpp/diagrams/item-07-parentheses-vs-braces");
      return {
        EmcppBraceSyntaxCoverageMap: module0.EmcppBraceSyntaxCoverageMap,
        EmcppInitializerListPreferenceMap:
          module0.EmcppInitializerListPreferenceMap,
        EmcppVectorConstructionSemanticsMap:
          module0.EmcppVectorConstructionSemanticsMap,
      } as ChapterMdxComponents;
    },
  "grokking-algorithms-2e/core-intuitions/hash-tables": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/hash-tables");
    return {
      HashFunctionArrayDiagram: module0.HashFunctionArrayDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/core-intuitions/quicksort": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/quicksort");
    return {
      DivideConquerFarmDiagram: module0.DivideConquerFarmDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/core-intuitions/recursion": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/recursion");
    return {
      RecursionSearchDiagram: module0.RecursionSearchDiagram,
      CallStackFramesDiagram: module0.CallStackFramesDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/core-intuitions/selection-sort": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/selection-sort");
    return {
      SelectionSortMemoryDiagram: module0.SelectionSortMemoryDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/next-steps/where-to-go-next": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/where-to-go-next");
    return {
      TopicRouteMap: module0.TopicRouteMap,
      RegressionIndexDiagram: module0.RegressionIndexDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/strategy-and-planning/greedy-algorithms":
    async () => {
      const module0 =
        await import("@/components/mdx/grokking-algorithms-2e/diagrams/greedy-algorithms");
      return {
        ClassroomScheduleDiagram: module0.ClassroomScheduleDiagram,
        NpSearchSpaceDiagram: module0.NpSearchSpaceDiagram,
      } as ChapterMdxComponents;
    },
  "grokking-algorithms-2e/strategy-and-planning/k-nearest-neighbors":
    async () => {
      const module0 =
        await import("@/components/mdx/grokking-algorithms-2e/diagrams/k-nearest-neighbors");
      return {
        FruitFeatureDiagram: module0.FruitFeatureDiagram,
        RecommendationFeatureMap: module0.RecommendationFeatureMap,
      } as ChapterMdxComponents;
    },
  "grokking-algorithms-2e/trees-and-graphs/balanced-trees": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/balanced-trees");
    return {
      BstShapeDiagram: module0.BstShapeDiagram,
      BTreePageDiagram: module0.BTreePageDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/trees-and-graphs/breadth-first-search": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/breadth-first-search");
    return {
      GraphDirectionDiagram: module0.GraphDirectionDiagram,
      BfsShortestPathDiagram: module0.BfsShortestPathDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/trees-and-graphs/dijkstras-algorithm": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/dijkstras-algorithm");
    return {
      WeightedPathDiagram: module0.WeightedPathDiagram,
      NegativeEdgeDiagram: module0.NegativeEdgeDiagram,
    } as ChapterMdxComponents;
  },
  "grokking-algorithms-2e/trees-and-graphs/trees": async () => {
    const module0 =
      await import("@/components/mdx/grokking-algorithms-2e/diagrams/trees");
    return {
      TreeAnatomyDiagram: module0.TreeAnatomyDiagram,
      HuffmanCodingDiagram: module0.HuffmanCodingDiagram,
    } as ChapterMdxComponents;
  },
  "head-first-design-patterns/04-advanced/hfd-compound-patterns": async () => {
    const module0 =
      await import("@/components/mdx/head-first-design-patterns/diagrams/hfd-compound-patterns");
    return {
      HfdCompoundPatternsDiagram: module0.HfdCompoundPatternsDiagram,
    } as ChapterMdxComponents;
  },
  "head-first-design-patterns/04-advanced/hfd-iterator-composite": async () => {
    const module0 =
      await import("@/components/mdx/head-first-design-patterns/diagrams/hfd-iterator-composite");
    return {
      HfdIteratorCompositeDiagram: module0.HfdIteratorCompositeDiagram,
    } as ChapterMdxComponents;
  },
  "head-first-design-patterns/04-advanced/hfd-proxy": async () => {
    const module0 =
      await import("@/components/mdx/head-first-design-patterns/diagrams/hfd-proxy");
    return {
      HfdProxyDiagram: module0.HfdProxyDiagram,
    } as ChapterMdxComponents;
  },
  "head-first-design-patterns/04-advanced/hfd-real-world": async () => {
    const module0 =
      await import("@/components/mdx/head-first-design-patterns/diagrams/hfd-real-world");
    return {
      HfdRealWorldDiagram: module0.HfdRealWorldDiagram,
    } as ChapterMdxComponents;
  },
  "head-first-design-patterns/04-advanced/hfd-state": async () => {
    const module0 =
      await import("@/components/mdx/head-first-design-patterns/diagrams/hfd-state");
    return {
      HfdStateDiagram: module0.HfdStateDiagram,
    } as ChapterMdxComponents;
  },
  "optimized-cpp/05-official/optimize-algorithms": async () => {
    const module0 =
      await import("@/components/mdx/optimized-cpp/diagrams/optimize-algorithms");
    return {
      OpcAlgorithmCostCaseMap: module0.OpcAlgorithmCostCaseMap,
      OpcAlgorithmWorkTransformationMap:
        module0.OpcAlgorithmWorkTransformationMap,
      OpcSearchSortDecisionMap: module0.OpcSearchSortDecisionMap,
    } as ChapterMdxComponents;
  },
  "poeaa-enterprise-patterns/00-map/poeaa24-official-learning-map":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-learning-map-diagram");
      return {
        Poeaa24LearningMapDiagram: module0.Poeaa24LearningMapDiagram,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/03-pattern-list/poeaa24-pattern-list":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-list-diagram");
      return {
        Poeaa24PatternListDiagram: module0.Poeaa24PatternListDiagram,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/06-chapter-01-layering/poeaa24-chapter-01-layering":
    async () => {
      const modules = await Promise.all([
        import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch01-layer-stack-diagram"),
        import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch01-deployment-diagram"),
      ]);
      return {
        Poeaa24Ch01LayerStackDiagram: modules[0].Poeaa24Ch01LayerStackDiagram,
        Poeaa24Ch01DeploymentDiagram: modules[1].Poeaa24Ch01DeploymentDiagram,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/07-chapter-02-organizing-domain-logic/poeaa24-chapter-02-organizing-domain-logic":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch02-domain-logic-strategies");
      return {
        Poeaa24Ch02DomainLogicStrategies:
          module0.Poeaa24Ch02DomainLogicStrategies,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/08-chapter-03-relational-mapping/poeaa24-chapter-03-relational-mapping":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch03-impedance-mismatch");
      return {
        Poeaa24Ch03ImpedanceMismatch: module0.Poeaa24Ch03ImpedanceMismatch,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/09-chapter-04-web-presentation/poeaa24-chapter-04-web-presentation":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch04-mvc-triangle");
      return {
        Poeaa24Ch04MvcTriangle: module0.Poeaa24Ch04MvcTriangle,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/10-chapter-05-concurrency/poeaa24-chapter-05-concurrency":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch05-optimistic-vs-pessimistic");
      return {
        Poeaa24Ch05OptimisticVsPessimistic:
          module0.Poeaa24Ch05OptimisticVsPessimistic,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/11-chapter-06-session-state/poeaa24-chapter-06-session-state":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch06-session-state-positions");
      return {
        Poeaa24Ch06SessionStatePositions:
          module0.Poeaa24Ch06SessionStatePositions,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/12-chapter-07-distribution-strategies/poeaa24-chapter-07-distribution-strategies":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch07-remote-call-cost");
      return {
        Poeaa24Ch07RemoteCallCost: module0.Poeaa24Ch07RemoteCallCost,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/13-chapter-08-putting-together/poeaa24-chapter-08-putting-together":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch08-assembly-diagram");
      return {
        Poeaa24Ch08AssemblyDiagram: module0.Poeaa24Ch08AssemblyDiagram,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/15-chapter-09-domain-logic-patterns/poeaa24-chapter-09-domain-logic-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch09-domain-logic-map");
      return {
        Poeaa24Ch09DomainLogicMap: module0.Poeaa24Ch09DomainLogicMap,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/16-pattern-01-transaction-script/poeaa24-pattern-01-transaction-script":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-01-transaction-script-diagram");
      return {
        Poeaa24Pattern01TransactionScript:
          module0.Poeaa24Pattern01TransactionScript,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/17-pattern-02-domain-model/poeaa24-pattern-02-domain-model":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-02-domain-model-diagram");
      return {
        Poeaa24Pattern02DomainModel: module0.Poeaa24Pattern02DomainModel,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/19-pattern-04-service-layer/poeaa24-pattern-04-service-layer":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-04-service-layer-diagram");
      return {
        Poeaa24Pattern04ServiceLayer: module0.Poeaa24Pattern04ServiceLayer,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/20-chapter-10-data-source-patterns/poeaa24-chapter-10-data-source-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch10-datasource-gradient");
      return {
        Poeaa24Ch10DataSourceGradient: module0.Poeaa24Ch10DataSourceGradient,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/21-pattern-05-table-data-gateway/poeaa24-pattern-05-table-data-gateway":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-05-table-data-gateway-diagram");
      return {
        Poeaa24Pattern05TableDataGateway:
          module0.Poeaa24Pattern05TableDataGateway,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/22-pattern-06-row-data-gateway/poeaa24-pattern-06-row-data-gateway":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-06-row-data-gateway-diagram");
      return {
        Poeaa24Pattern06RowDataGateway: module0.Poeaa24Pattern06RowDataGateway,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/23-pattern-07-active-record/poeaa24-pattern-07-active-record":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-07-active-record-diagram");
      return {
        Poeaa24Pattern07ActiveRecord: module0.Poeaa24Pattern07ActiveRecord,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/24-pattern-08-data-mapper/poeaa24-pattern-08-data-mapper":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-08-data-mapper-diagram");
      return {
        Poeaa24Pattern08DataMapper: module0.Poeaa24Pattern08DataMapper,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/25-chapter-11-object-relational-behavior/poeaa24-chapter-11-object-relational-behavior":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch11-behavior-collaboration");
      return {
        Poeaa24Ch11BehaviorCollaboration:
          module0.Poeaa24Ch11BehaviorCollaboration,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/26-pattern-09-unit-of-work/poeaa24-pattern-09-unit-of-work":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-09-unit-of-work-diagram");
      return {
        Poeaa24Pattern09UnitOfWork: module0.Poeaa24Pattern09UnitOfWork,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/27-pattern-10-identity-map/poeaa24-pattern-10-identity-map":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-10-identity-map-diagram");
      return {
        Poeaa24Pattern10IdentityMap: module0.Poeaa24Pattern10IdentityMap,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/29-chapter-12-object-relational-structure/poeaa24-chapter-12-object-relational-structure":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch12-structure-decision-tree");
      return {
        Poeaa24Ch12StructureDecisionTree:
          module0.Poeaa24Ch12StructureDecisionTree,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/30-pattern-12-identity-field/poeaa24-pattern-12-identity-field":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-12-identity-field-diagram");
      return {
        Poeaa24Pattern12IdentityField: module0.Poeaa24Pattern12IdentityField,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/31-pattern-13-foreign-key-mapping/poeaa24-pattern-13-foreign-key-mapping":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-13-foreign-key-mapping-diagram");
      return {
        Poeaa24Pattern13ForeignKeyMapping:
          module0.Poeaa24Pattern13ForeignKeyMapping,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/32-pattern-14-association-table-mapping/poeaa24-pattern-14-association-table-mapping":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-14-association-table-mapping-diagram");
      return {
        Poeaa24Pattern14AssociationTableMapping:
          module0.Poeaa24Pattern14AssociationTableMapping,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/33-pattern-15-dependent-mapping/poeaa24-pattern-15-dependent-mapping":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-15-dependent-mapping-diagram");
      return {
        Poeaa24Pattern15DependentMapping:
          module0.Poeaa24Pattern15DependentMapping,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/34-pattern-16-embedded-value/poeaa24-pattern-16-embedded-value":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-16-embedded-value-diagram");
      return {
        Poeaa24Pattern16EmbeddedValue: module0.Poeaa24Pattern16EmbeddedValue,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/35-pattern-17-serialized-lob/poeaa24-pattern-17-serialized-lob":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-17-serialized-lob-diagram");
      return {
        Poeaa24Pattern17SerializedLob: module0.Poeaa24Pattern17SerializedLob,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/36-pattern-18-single-table-inheritance/poeaa24-pattern-18-single-table-inheritance":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-18-single-table-inheritance-diagram");
      return {
        Poeaa24Pattern18SingleTableInheritance:
          module0.Poeaa24Pattern18SingleTableInheritance,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/37-pattern-19-class-table-inheritance/poeaa24-pattern-19-class-table-inheritance":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-19-class-table-inheritance-diagram");
      return {
        Poeaa24Pattern19ClassTableInheritance:
          module0.Poeaa24Pattern19ClassTableInheritance,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/38-pattern-20-concrete-table-inheritance/poeaa24-pattern-20-concrete-table-inheritance":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-20-concrete-table-inheritance-diagram");
      return {
        Poeaa24Pattern20ConcreteTableInheritance:
          module0.Poeaa24Pattern20ConcreteTableInheritance,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/39-pattern-21-inheritance-mappers/poeaa24-pattern-21-inheritance-mappers":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-21-inheritance-mappers-diagram");
      return {
        Poeaa24Pattern21InheritanceMappers:
          module0.Poeaa24Pattern21InheritanceMappers,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/40-chapter-13-object-relational-metadata/poeaa24-chapter-13-object-relational-metadata":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch13-metadata-compare");
      return {
        Poeaa24Ch13MetadataCompare: module0.Poeaa24Ch13MetadataCompare,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/41-pattern-22-metadata-mapping/poeaa24-pattern-22-metadata-mapping":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-22-metadata-mapping-diagram");
      return {
        Poeaa24Pattern22MetadataMapping:
          module0.Poeaa24Pattern22MetadataMapping,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/42-pattern-23-query-object/poeaa24-pattern-23-query-object":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-23-query-object-diagram");
      return {
        Poeaa24Pattern23QueryObject: module0.Poeaa24Pattern23QueryObject,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/43-pattern-24-repository/poeaa24-pattern-24-repository":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-24-repository-diagram");
      return {
        Poeaa24Pattern24Repository: module0.Poeaa24Pattern24Repository,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/44-chapter-14-web-presentation-patterns/poeaa24-chapter-14-web-presentation-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch14-web-presentation-matrix");
      return {
        Poeaa24Ch14WebPresentationMatrix:
          module0.Poeaa24Ch14WebPresentationMatrix,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/45-pattern-25-model-view-controller/poeaa24-pattern-25-model-view-controller":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-25-model-view-controller-diagram");
      return {
        Poeaa24Pattern25ModelViewController:
          module0.Poeaa24Pattern25ModelViewController,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/46-pattern-26-page-controller/poeaa24-pattern-26-page-controller":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-26-page-controller-diagram");
      return {
        Poeaa24Pattern26PageController: module0.Poeaa24Pattern26PageController,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/47-pattern-27-front-controller/poeaa24-pattern-27-front-controller":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-27-front-controller-diagram");
      return {
        Poeaa24Pattern27FrontController:
          module0.Poeaa24Pattern27FrontController,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/48-pattern-28-template-view/poeaa24-pattern-28-template-view":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-28-template-view-diagram");
      return {
        Poeaa24Pattern28TemplateView: module0.Poeaa24Pattern28TemplateView,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/49-pattern-29-transform-view/poeaa24-pattern-29-transform-view":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-29-transform-view-diagram");
      return {
        Poeaa24Pattern29TransformView: module0.Poeaa24Pattern29TransformView,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/50-pattern-30-two-step-view/poeaa24-pattern-30-two-step-view":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-30-two-step-view-diagram");
      return {
        Poeaa24Pattern30TwoStepView: module0.Poeaa24Pattern30TwoStepView,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/51-pattern-31-application-controller/poeaa24-pattern-31-application-controller":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-31-application-controller-diagram");
      return {
        Poeaa24Pattern31ApplicationController:
          module0.Poeaa24Pattern31ApplicationController,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/52-chapter-15-distribution-patterns/poeaa24-chapter-15-distribution-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch15-distribution-callstack");
      return {
        Poeaa24Ch15DistributionCallStack:
          module0.Poeaa24Ch15DistributionCallStack,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/53-pattern-32-remote-facade/poeaa24-pattern-32-remote-facade":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-32-remote-facade-diagram");
      return {
        Poeaa24Pattern32RemoteFacade: module0.Poeaa24Pattern32RemoteFacade,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/54-pattern-33-data-transfer-object/poeaa24-pattern-33-data-transfer-object":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-33-data-transfer-object-diagram");
      return {
        Poeaa24Pattern33DataTransferObject:
          module0.Poeaa24Pattern33DataTransferObject,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/55-chapter-16-offline-concurrency-patterns/poeaa24-chapter-16-offline-concurrency-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch16-lock-strategies");
      return {
        Poeaa24Ch16LockStrategies: module0.Poeaa24Ch16LockStrategies,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/56-pattern-34-optimistic-offline-lock/poeaa24-pattern-34-optimistic-offline-lock":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-34-optimistic-offline-lock-diagram");
      return {
        Poeaa24Pattern34OptimisticOfflineLock:
          module0.Poeaa24Pattern34OptimisticOfflineLock,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/57-pattern-35-pessimistic-offline-lock/poeaa24-pattern-35-pessimistic-offline-lock":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-35-pessimistic-offline-lock-diagram");
      return {
        Poeaa24Pattern35PessimisticOfflineLock:
          module0.Poeaa24Pattern35PessimisticOfflineLock,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/58-pattern-36-coarse-grained-lock/poeaa24-pattern-36-coarse-grained-lock":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-36-coarse-grained-lock-diagram");
      return {
        Poeaa24Pattern36CoarseGrainedLock:
          module0.Poeaa24Pattern36CoarseGrainedLock,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/59-pattern-37-implicit-lock/poeaa24-pattern-37-implicit-lock":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-37-implicit-lock-diagram");
      return {
        Poeaa24Pattern37ImplicitLock: module0.Poeaa24Pattern37ImplicitLock,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/61-pattern-38-client-session-state/poeaa24-pattern-38-client-session-state":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-38-client-session-state-diagram");
      return {
        Poeaa24Pattern38ClientSessionState:
          module0.Poeaa24Pattern38ClientSessionState,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/62-pattern-39-server-session-state/poeaa24-pattern-39-server-session-state":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-39-server-session-state-diagram");
      return {
        Poeaa24Pattern39ServerSessionState:
          module0.Poeaa24Pattern39ServerSessionState,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/63-pattern-40-database-session-state/poeaa24-pattern-40-database-session-state":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-40-database-session-state-diagram");
      return {
        Poeaa24Pattern40DatabaseSessionState:
          module0.Poeaa24Pattern40DatabaseSessionState,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/64-chapter-18-base-patterns/poeaa24-chapter-18-base-patterns":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-ch18-base-patterns-deps");
      return {
        Poeaa24Ch18BasePatternsDeps: module0.Poeaa24Ch18BasePatternsDeps,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/65-pattern-41-gateway/poeaa24-pattern-41-gateway":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-41-gateway-diagram");
      return {
        Poeaa24Pattern41Gateway: module0.Poeaa24Pattern41Gateway,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/66-pattern-42-mapper/poeaa24-pattern-42-mapper":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-42-mapper-diagram");
      return {
        Poeaa24Pattern42Mapper: module0.Poeaa24Pattern42Mapper,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/67-pattern-43-layer-supertype/poeaa24-pattern-43-layer-supertype":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-43-layer-supertype-diagram");
      return {
        Poeaa24Pattern43LayerSupertype: module0.Poeaa24Pattern43LayerSupertype,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/68-pattern-44-separated-interface/poeaa24-pattern-44-separated-interface":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-44-separated-interface-diagram");
      return {
        Poeaa24Pattern44SeparatedInterface:
          module0.Poeaa24Pattern44SeparatedInterface,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/69-pattern-45-registry/poeaa24-pattern-45-registry":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-45-registry-diagram");
      return {
        Poeaa24Pattern45Registry: module0.Poeaa24Pattern45Registry,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/72-pattern-48-special-case/poeaa24-pattern-48-special-case":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-48-special-case-diagram");
      return {
        Poeaa24Pattern48SpecialCase: module0.Poeaa24Pattern48SpecialCase,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/73-pattern-49-plugin/poeaa24-pattern-49-plugin":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-49-plugin-diagram");
      return {
        Poeaa24Pattern49Plugin: module0.Poeaa24Pattern49Plugin,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/74-pattern-50-service-stub/poeaa24-pattern-50-service-stub":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-50-service-stub-diagram");
      return {
        Poeaa24Pattern50ServiceStub: module0.Poeaa24Pattern50ServiceStub,
      } as ChapterMdxComponents;
    },
  "poeaa-enterprise-patterns/75-pattern-51-record-set/poeaa24-pattern-51-record-set":
    async () => {
      const module0 =
        await import("@/components/mdx/poeaa-enterprise-patterns/diagrams/poeaa24-pattern-51-record-set-diagram");
      return {
        Poeaa24Pattern51RecordSet: module0.Poeaa24Pattern51RecordSet,
      } as ChapterMdxComponents;
    },
  "programming-pearls/01-preliminaries/02-aha-algorithms": async () => {
    const module0 =
      await import("@/components/mdx/programming-pearls/diagrams/02-aha-algorithms");
    return {
      PP2ThreeProblemsMap: module0.PP2ThreeProblemsMap,
    } as ChapterMdxComponents;
  },
};

export async function getChapterMdxComponents(
  bookSlug: string,
  sectionSlug: string,
  chapterSlug: string,
): Promise<ChapterMdxComponents> {
  const route = `${bookSlug}/${sectionSlug}/${chapterSlug}`;
  return chapterComponentLoaders[route]?.() ?? {};
}
