"use client";
import { useMemo, useState } from "react";

type Mode = "graph" | "schedule" | "evidence";
type Props = { mode: Mode; unitTitle: string; focus: string; nodes: string[] };
const evidenceGates = ["对象图与根", "算法不变式", "原始测量", "失败反例", "版本与回滚"];

export function OfficialGchBookLab({ mode, unitTitle, focus, nodes }: Props) {
  const [selected, setSelected] = useState(0);
  const [allocationRate, setAllocationRate] = useState(48);
  const [liveRatio, setLiveRatio] = useState(35);
  const [checked, setChecked] = useState([true, false, false, false, false]);
  function resetExperiment() {
    setSelected(0);
    setAllocationRate(48);
    setLiveRatio(35);
    setChecked([true, false, false, false, false]);
  }

  const visible = nodes.slice(0, 18);
  const score = useMemo(() => checked.filter(Boolean).length * 20, [checked]);
  const traceWork = Math.round(allocationRate * (0.35 + liveRatio / 100));
  const reserve = Math.max(0, 100 - Math.round(liveRatio * 0.8 + allocationRate * 0.45));

  if (mode === "graph") return <section className="my-6 overflow-hidden rounded-md border border-zinc-300 bg-white text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "对象图实验"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><header className="border-b border-zinc-200 bg-emerald-50 px-4 py-3 dark:border-zinc-800 dark:bg-emerald-950/40"><p className="m-0 text-xs font-semibold uppercase text-emerald-800 dark:text-emerald-300">Object graph and invariant</p><h3 className="m-0 mt-1 text-base font-bold">{unitTitle}</h3></header><div className="grid min-h-[310px] md:grid-cols-[minmax(0,1.2fr)_minmax(240px,0.8fr)]"><div className="grid content-start grid-cols-1 gap-2 border-b border-zinc-200 p-4 sm:grid-cols-2 md:border-b-0 md:border-r dark:border-zinc-800">{visible.map((node, index) => <button key={node} type="button" onClick={() => setSelected(index)} aria-pressed={selected === index} className={"min-h-12 rounded border px-3 py-2 text-left text-xs font-medium " + (selected === index ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-300 bg-zinc-50 text-zinc-800 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100")}><span className="mr-2 font-mono">{String(index + 1).padStart(2, "0")}</span>{node}</button>)}</div><div className="p-4"><p className="m-0 text-xs font-semibold text-rose-700 dark:text-rose-300">当前正式节点</p><p className="mt-2 min-h-12 text-sm font-bold">{visible[selected] ?? unitTitle}</p><p className="mt-3 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p><p className="mt-4 border-l-4 border-amber-500 pl-3 text-xs leading-5 text-zinc-600 dark:text-zinc-400">先标根、对象、边和颜色，再讨论算法或产品实现。</p></div></div></section>;

  if (mode === "schedule") return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "调度实验"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><div className="border-b border-zinc-200 pb-3 dark:border-zinc-800"><p className="m-0 text-xs font-semibold text-cyan-700 dark:text-cyan-300">Work and space budget</p><h3 className="m-0 mt-1 text-base font-bold">分配、存活与余量</h3></div><label htmlFor={unitTitle + "-allocation"} className="mt-4 block text-sm font-medium">分配速率：{allocationRate} MB/s</label><input id={unitTitle + "-allocation"} type="range" min="4" max="120" value={allocationRate} onChange={(event) => setAllocationRate(Number(event.target.value))} className="mt-2 w-full accent-cyan-700" /><label htmlFor={unitTitle + "-live"} className="mt-4 block text-sm font-medium">存活比例：{liveRatio}%</label><input id={unitTitle + "-live"} type="range" min="5" max="95" value={liveRatio} onChange={(event) => setLiveRatio(Number(event.target.value))} className="mt-2 w-full accent-cyan-700" /><div className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded border border-zinc-300 bg-zinc-300 dark:border-zinc-700 dark:bg-zinc-700"><div className="bg-white p-3 dark:bg-zinc-950"><p className="m-0 text-xs text-zinc-500">示意追踪工作</p><p className="m-0 mt-1 text-xl font-bold text-rose-700 dark:text-rose-300">{traceWork} units</p></div><div className="bg-white p-3 dark:bg-zinc-950"><p className="m-0 text-xs text-zinc-500">示意疏散余量</p><p className="m-0 mt-1 text-xl font-bold text-emerald-700 dark:text-emerald-300">{reserve}%</p></div></div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p><p className="mt-2 text-xs leading-5 text-zinc-600 dark:text-zinc-400">数值只用于观察方向；正式结论必须来自固定负载、原始日志和独立重放。</p></section>;

  return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "证据门"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><div className="flex items-center justify-between gap-3"><div><p className="m-0 text-xs font-semibold text-violet-700 dark:text-violet-300">Evidence gate</p><h3 className="m-0 mt-1 text-base font-bold">回收算法证据完整度</h3></div><output className="min-w-16 rounded border border-zinc-300 px-3 py-2 text-center text-lg font-bold dark:border-zinc-700">{score}%</output></div><div className="mt-4 divide-y divide-zinc-200 border-y border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800">{evidenceGates.map((gate, index) => <button key={gate} type="button" onClick={() => setChecked((current) => current.map((value, item) => item === index ? !value : value))} aria-pressed={checked[index]} className="flex min-h-11 w-full items-center justify-between gap-3 px-2 text-left text-sm hover:bg-zinc-50 dark:hover:bg-zinc-900"><span>{gate}</span><span className={"inline-flex h-6 w-6 items-center justify-center rounded border font-bold " + (checked[index] ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-400 text-transparent")}>✓</span></button>)}</div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{score === 100 ? "证据齐全：交给另一位读者更换对象图和负载尝试推翻结论。" : "尚未闭环：对象图、证明、测量、反例和回滚必须同时成立。"}</p><p className="mt-3 text-xs leading-5 text-zinc-600 dark:text-zinc-400">{focus}</p></section>;
}
