"use client";

import { useId, useState, type ReactNode } from "react";

export type GameMathMode="roadmap"|"coordinate"|"vector"|"spaces"|"matrix"|"transform"|"polar"|"rotation"|"geometry"|"graphics"|"kinematics"|"dynamics"|"curves"|"tests";
export interface GameMathSnapshot{label:string;input:string;operation:string;output:string;risk:string}

export function GameMathOfficialLab({title,caption,mode,snapshots,initial=0}:{title:string;caption:string;mode:GameMathMode;snapshots:ReadonlyArray<GameMathSnapshot>;initial?:number}){
  const [selected,setSelected]=useState(Math.min(initial,snapshots.length-1));
  const [progress,setProgress]=useState(.58);const [angle,setAngle]=useState(32);const [scale,setScale]=useState(1.15);
  const marker=useId().replaceAll(":","");const item=snapshots[selected];
  const reset=()=>{setSelected(Math.min(initial,snapshots.length-1));setProgress(.58);setAngle(32);setScale(1.15)};
  return <figure className="not-prose my-6"><div className="border border-border bg-elevated p-4 sm:p-5"><div className="flex items-center justify-between gap-3 border-b border-border pb-3"><div><strong className="text-sm text-primary">{title}</strong><p className="mt-1 text-xs text-secondary">{caption}</p></div><button type="button" onClick={reset} title="重置实验" aria-label="重置实验" className="grid size-11 shrink-0 place-items-center border border-border bg-bg text-lg text-secondary hover:border-accent hover:text-primary"><span aria-hidden="true">↺</span></button></div><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.35fr)_minmax(16rem,.65fr)]"><div><svg viewBox="0 0 640 360" role="img" aria-label={title} className="aspect-video w-full border border-border bg-bg"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" className="fill-accent"/></marker></defs>{scene(mode,progress,angle,scale,marker)}</svg><div className="mt-3 grid grid-cols-5 gap-1">{snapshots.map((x,i)=><button key={x.label} type="button" onClick={()=>setSelected(i)} aria-pressed={selected===i} className={`min-h-14 border px-1 py-2 text-[11px] leading-4 ${selected===i?"border-accent bg-accent/10 text-primary":"border-border bg-bg text-secondary"}`}>{x.label}</button>)}</div></div><div className="grid content-start gap-3"><Control label="进度" value={progress} min={0} max={1} step={.01} text={Math.round(progress*100)+"%"} set={setProgress}/><Control label="角度" value={angle} min={-90} max={90} step={1} text={angle+" deg"} set={setAngle}/><Control label="尺度" value={scale} min={.5} max={1.8} step={.01} text={scale.toFixed(2)+"x"} set={setScale}/><Cell label="输入 / 空间" value={item.input}/><Cell label="运算 / 假设" value={item.operation}/><Cell label="输出 / 证据" value={item.output}/><div className="border border-rose-500/40 bg-rose-500/10 p-3 text-xs leading-5 text-primary"><span className="font-semibold">边界：</span>{item.risk}</div></div></div></div></figure>;
}

function Control({label,value,min,max,step,text,set}:{label:string;value:number;min:number;max:number;step:number;text:string;set:(v:number)=>void}){return <label className="grid gap-1 text-xs text-secondary"><span className="flex justify-between gap-3">{label}<strong className="font-mono text-primary">{text}</strong></span><input className="h-1 w-full cursor-pointer accent-cyan-500" type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>}
function Cell({label,value}:{label:string;value:string}){return <div className="min-h-20 border border-border bg-bg p-3"><span className="text-[11px] text-secondary">{label}</span><strong className="mt-1 block text-xs leading-5 text-primary">{value}</strong></div>}

function axes(marker:string){return <g><line x1="70" y1="280" x2="580" y2="280" className="stroke-secondary" markerEnd={`url(#${marker})`}/><line x1="110" y1="320" x2="110" y2="45" className="stroke-secondary" markerEnd={`url(#${marker})`}/>{[180,250,320,390,460,530].map(x=><line key={x} x1={x} y1="65" x2={x} y2="300" className="stroke-border"/>)}{[100,145,190,235].map(y=><line key={y} x1="85" y1={y} x2="570" y2={y} className="stroke-border"/>)}</g>}
function scene(mode:GameMathMode,t:number,deg:number,scale:number,marker:string):ReactNode{const a=deg*Math.PI/180;const x=280+150*t*Math.cos(a)*scale;const y=230-130*t*Math.sin(a)*scale;const arrow={markerEnd:`url(#${marker})`};switch(mode){
case "coordinate":return <g>{axes(marker)}<line x1="110" y1="280" x2={x} y2={y} className="stroke-cyan-500" strokeWidth="4" {...arrow}/><line x1={x} y1={y} x2={x} y2="280" className="stroke-amber-500" strokeDasharray="7 5"/><circle cx={x} cy={y} r="8" className="fill-emerald-500"/><text x={x+12} y={y-10} className="fill-primary text-sm">P(x,y)</text></g>;
case "vector":return <g>{axes(marker)}<line x1="150" y1="260" x2={x} y2={y} className="stroke-cyan-500" strokeWidth="5" {...arrow}/><line x1={x} y1={y} x2={x+90*scale} y2={y-35} className="stroke-amber-500" strokeWidth="5" {...arrow}/><line x1="150" y1="260" x2={x+90*scale} y2={y-35} className="stroke-emerald-500" strokeWidth="3" strokeDasharray="8 5" {...arrow}/></g>;
case "spaces":return <g>{axes(marker)}<g transform={`translate(260 180) rotate(${deg}) scale(${scale})`}><line x1="0" y1="0" x2="130" y2="0" className="stroke-cyan-500" strokeWidth="5" {...arrow}/><line x1="0" y1="0" x2="0" y2="-105" className="stroke-amber-500" strokeWidth="5" {...arrow}/><rect x="25" y="-70" width="70" height="50" className="fill-cyan-500/20 stroke-cyan-500"/></g><circle cx="260" cy="180" r="7" className="fill-emerald-500"/></g>;
case "matrix":case "transform":return <g>{axes(marker)}<g transform={`translate(250 205) rotate(${deg*t}) skewX(${18*t}) scale(${scale})`}><path d="M-70 55 L55 55 L10 -65 Z" className="fill-cyan-500/20 stroke-cyan-500" strokeWidth="4"/><line x1="0" y1="0" x2="100" y2="0" className="stroke-emerald-500" strokeWidth="4" {...arrow}/><line x1="0" y1="0" x2="0" y2="-90" className="stroke-amber-500" strokeWidth="4" {...arrow}/></g></g>;
case "polar":return <g>{axes(marker)}{[45,90,135].map(r=><circle key={r} cx="310" cy="190" r={r*scale/1.2} className="fill-none stroke-border"/>)}<line x1="310" y1="190" x2={310+140*t*Math.cos(a)} y2={190-140*t*Math.sin(a)} className="stroke-cyan-500" strokeWidth="5" {...arrow}/><circle cx={310+140*t*Math.cos(a)} cy={190-140*t*Math.sin(a)} r="8" className="fill-emerald-500"/></g>;
case "rotation":return <g>{axes(marker)}<g transform={`translate(320 190) rotate(${deg*t}) scale(${scale})`}><rect x="-75" y="-75" width="150" height="150" className="fill-cyan-500/15 stroke-cyan-500" strokeWidth="4"/><line x1="0" y1="0" x2="105" y2="0" className="stroke-amber-500" strokeWidth="5" {...arrow}/><path d="M-35 -95 A100 100 0 0 1 70 -70" className="fill-none stroke-emerald-500" strokeWidth="4" {...arrow}/></g></g>;
case "geometry":case "tests":return <g>{axes(marker)}<rect x="360" y="115" width={105*scale} height={115*scale} className="fill-amber-500/10 stroke-amber-500" strokeWidth="4"/><circle cx="300" cy="190" r={58*scale} className="fill-cyan-500/10 stroke-cyan-500" strokeWidth="4"/><line x1="85" y1={260-90*t} x2="560" y2={100+80*t} className="stroke-emerald-500" strokeWidth="5" {...arrow}/><path d="M170 270 L245 115 L325 270 Z" className="fill-none stroke-secondary" strokeWidth="3"/></g>;
case "graphics":return <g>{[70,190,310,430].map((x,i)=><g key={x}><rect x={x} y={120+(i%2)*30} width="105" height="70" className={i===Math.floor(t*4)%4?"fill-cyan-500/25 stroke-cyan-500":"fill-elevated stroke-border"} strokeWidth="3"/><text x={x+52} y={160+(i%2)*30} textAnchor="middle" className="fill-primary text-sm">{["model","view/clip","raster","shade"][i]}</text>{i<3&&<line x1={x+105} y1={155+(i%2)*30} x2={x+120} y2={155+((i+1)%2)*30} className="stroke-emerald-500" strokeWidth="3" {...arrow}/>}</g>)}</g>;
case "kinematics":case "dynamics":return <g>{axes(marker)}<path d={`M110 270 Q300 ${60+100*(1-t)} 560 245`} className="fill-none stroke-cyan-500" strokeWidth="5"/><circle cx={110+450*t} cy={270-180*Math.sin(Math.PI*t)} r={18*scale} className="fill-amber-500"/><line x1={110+450*t} y1={270-180*Math.sin(Math.PI*t)} x2={170+450*t} y2={230-180*Math.sin(Math.PI*t)} className="stroke-emerald-500" strokeWidth="5" {...arrow}/></g>;
case "curves":return <g>{axes(marker)}<path d="M110 270 C170 70 440 60 550 245" className="fill-none stroke-cyan-500" strokeWidth="6"/><path d="M110 270 L170 70 L440 60 L550 245" className="fill-none stroke-secondary" strokeDasharray="8 6"/>{[[110,270],[170,70],[440,60],[550,245]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r={i===Math.round(t*3)?10:7} className={i===Math.round(t*3)?"fill-amber-500":"fill-emerald-500"}/>)}</g>;
default:return <g>{axes(marker)}{[100,200,300,400,500].map((cx,i)=><g key={cx}><circle cx={cx} cy={i%2?130:235} r={26+8*t} className={i===Math.floor(t*5)%5?"fill-cyan-500 stroke-cyan-500":"fill-elevated stroke-border"} strokeWidth="3"/>{i<4&&<line x1={cx+28} y1={i%2?140:225} x2={cx+70} y2={(i+1)%2?130:235} className="stroke-emerald-500" strokeWidth="3" {...arrow}/>}</g>)}</g>}}
