import { OfficialJvt2Lab } from "./official-jvt2-lab";

const nodes = [
  "6 Finding hidden problems using profiling techniques",
  "6.1 Sampling to observe executing code",
  "6.2 Profiling to learn how many times a method is executed",
  "6.3 Using a profiler to identify SQL queries an app executes",
  "6.3.1 Using a profiler to retrieve SQL queries not generated by a framework",
  "6.3.2 Using the profiler to get the SQL queries generated by a framework",
  "6.3.3 Using the profiler to get programmatically generated SQL queries",
  "Summary"
];

export function Jvt2InvestigationLab() {
  return <OfficialJvt2Lab mode="investigation" unitTitle="第6章 用剖析发现隐藏问题" focus="比较采样与插桩，核对方法调用频次，并从直接、框架生成和动态构造三类路径恢复真实SQL" nodes={nodes} />;
}

export function Jvt2TimelineLab() {
  return <OfficialJvt2Lab mode="timeline" unitTitle="第6章 用剖析发现隐藏问题" focus="制造一个N+1查询和一个低频慢查询，验证频次、总成本与单次成本能将两者区分" nodes={nodes} />;
}

export function Jvt2EvidenceLab() {
  return <OfficialJvt2Lab mode="evidence" unitTitle="第6章 用剖析发现隐藏问题" focus="采样与插桩对照、调用频次表、SQL来源链、绑定参数分类、计划与索引证据" nodes={nodes} />;
}
