/**
 * <JvtJvmToolsDiagram>：JVM 诊断工具体系图解。
 * 纯静态展示，无交互。Server Component（不加 "use client"）。
 * 全部 DESIGN token 配色，无裸 hex。
 */

const VIEW_W = 740;
const VIEW_H = 460;

export function JvtJvmToolsDiagram() {
  return (
    <figure className="mdx-figure not-prose mx-auto my-6">
      <div className="overflow-hidden rounded-card border border-border bg-elevated p-5">
        <svg
          viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
          role="img"
          aria-label="JVM诊断工具体系图解"
          className="mx-auto block h-auto w-full max-w-[740px]"
        >
          <text
            x={VIEW_W / 2}
            y="26"
            textAnchor="middle"
            fontSize="16"
            fontWeight="700"
            fill="var(--text-primary)"
          >
            JVM 诊断工具体系
          </text>

          {/* 命令行工具 */}
          <text
            x="40"
            y="54"
            fontSize="13"
            fontWeight="600"
            fill="var(--warning)"
          >
            JDK 命令行工具
          </text>

          <rect
            x="40"
            y="62"
            width="130"
            height="70"
            rx="6"
            fill="var(--warning)"
            fillOpacity="0.10"
            stroke="var(--warning)"
            strokeWidth="1.2"
          />
          <text
            x="105"
            y="82"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--warning)"
          >
            jps
          </text>
          <text
            x="105"
            y="98"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            列 JVM 进程
          </text>
          <text
            x="105"
            y="114"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            pid + 主类名
          </text>

          <rect
            x="180"
            y="62"
            width="130"
            height="70"
            rx="6"
            fill="var(--warning)"
            fillOpacity="0.10"
            stroke="var(--warning)"
            strokeWidth="1.2"
          />
          <text
            x="245"
            y="82"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--warning)"
          >
            jstat
          </text>
          <text
            x="245"
            y="98"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            GC/类加载统计
          </text>
          <text
            x="245"
            y="114"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            -gc/-gcutil
          </text>

          <rect
            x="320"
            y="62"
            width="130"
            height="70"
            rx="6"
            fill="var(--warning)"
            fillOpacity="0.10"
            stroke="var(--warning)"
            strokeWidth="1.2"
          />
          <text
            x="385"
            y="82"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--warning)"
          >
            jmap
          </text>
          <text
            x="385"
            y="98"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            堆内存分析
          </text>
          <text
            x="385"
            y="114"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            -dump/-histo
          </text>

          <rect
            x="460"
            y="62"
            width="130"
            height="70"
            rx="6"
            fill="var(--warning)"
            fillOpacity="0.10"
            stroke="var(--warning)"
            strokeWidth="1.2"
          />
          <text
            x="525"
            y="82"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--warning)"
          >
            jstack
          </text>
          <text
            x="525"
            y="98"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            线程栈 dump
          </text>
          <text
            x="525"
            y="114"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            死锁/热点定位
          </text>

          <rect
            x="600"
            y="62"
            width="100"
            height="70"
            rx="6"
            fill="var(--warning)"
            fillOpacity="0.16"
            stroke="var(--warning)"
            strokeWidth="1.2"
          />
          <text
            x="650"
            y="82"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--warning)"
          >
            jcmd
          </text>
          <text
            x="650"
            y="98"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            统一命令
          </text>
          <text
            x="650"
            y="114"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            JDK7+ 首选
          </text>

          {/* CPU 热点定位流程 */}
          <text
            x="40"
            y="160"
            fontSize="13"
            fontWeight="600"
            fill="var(--danger)"
          >
            CPU 热点定位流程（不停机）
          </text>

          <rect
            x="40"
            y="168"
            width="120"
            height="44"
            rx="6"
            fill="var(--danger)"
            fillOpacity="0.10"
            stroke="var(--danger)"
            strokeWidth="1"
          />
          <text
            x="100"
            y="186"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--danger)"
          >
            1. top 进程
          </text>
          <text
            x="100"
            y="202"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            找 Java pid
          </text>

          <text
            x="170"
            y="192"
            textAnchor="middle"
            fontSize="14"
            fill="var(--text-tertiary)"
          >
            &rarr;
          </text>

          <rect
            x="185"
            y="168"
            width="120"
            height="44"
            rx="6"
            fill="var(--danger)"
            fillOpacity="0.10"
            stroke="var(--danger)"
            strokeWidth="1"
          />
          <text
            x="245"
            y="186"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--danger)"
          >
            2. top -Hp 线程
          </text>
          <text
            x="245"
            y="202"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            找高 CPU tid
          </text>

          <text
            x="315"
            y="192"
            textAnchor="middle"
            fontSize="14"
            fill="var(--text-tertiary)"
          >
            &rarr;
          </text>

          <rect
            x="330"
            y="168"
            width="120"
            height="44"
            rx="6"
            fill="var(--danger)"
            fillOpacity="0.10"
            stroke="var(--danger)"
            strokeWidth="1"
          />
          <text
            x="390"
            y="186"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--danger)"
          >
            3. tid 转十六进制
          </text>
          <text
            x="390"
            y="202"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            printf &apos;%x&apos;
          </text>

          <text
            x="460"
            y="192"
            textAnchor="middle"
            fontSize="14"
            fill="var(--text-tertiary)"
          >
            &rarr;
          </text>

          <rect
            x="475"
            y="168"
            width="120"
            height="44"
            rx="6"
            fill="var(--danger)"
            fillOpacity="0.10"
            stroke="var(--danger)"
            strokeWidth="1"
          />
          <text
            x="535"
            y="186"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--danger)"
          >
            4. jstack 找栈
          </text>
          <text
            x="535"
            y="202"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            nid=0xtid
          </text>

          <text
            x="605"
            y="192"
            textAnchor="middle"
            fontSize="14"
            fill="var(--text-tertiary)"
          >
            &rarr;
          </text>

          <rect
            x="620"
            y="168"
            width="80"
            height="44"
            rx="6"
            fill="var(--success)"
            fillOpacity="0.16"
            stroke="var(--success)"
            strokeWidth="1"
          />
          <text
            x="660"
            y="186"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--success)"
          >
            栈顶=热点
          </text>
          <text
            x="660"
            y="202"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            定位代码
          </text>

          {/* 可视化/在线工具 */}
          <text
            x="40"
            y="240"
            fontSize="13"
            fontWeight="600"
            fill="var(--accent)"
          >
            可视化与在线诊断工具
          </text>

          <rect
            x="40"
            y="248"
            width="160"
            height="80"
            rx="6"
            fill="var(--accent)"
            fillOpacity="0.10"
            stroke="var(--accent)"
            strokeWidth="1.2"
          />
          <text
            x="120"
            y="268"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--accent)"
          >
            JConsole
          </text>
          <text
            x="120"
            y="286"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            JMX 实时监控
          </text>
          <text
            x="120"
            y="302"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            内存/线程/MBean
          </text>
          <text
            x="120"
            y="318"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            简单开箱即用
          </text>

          <rect
            x="210"
            y="248"
            width="160"
            height="80"
            rx="6"
            fill="var(--accent)"
            fillOpacity="0.10"
            stroke="var(--accent)"
            strokeWidth="1.2"
          />
          <text
            x="290"
            y="268"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--accent)"
          >
            VisualVM
          </text>
          <text
            x="290"
            y="286"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            监控+采样一体
          </text>
          <text
            x="290"
            y="302"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            堆直方图/dump
          </text>
          <text
            x="290"
            y="318"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            中度分析
          </text>

          <rect
            x="380"
            y="248"
            width="160"
            height="80"
            rx="6"
            fill="var(--accent)"
            fillOpacity="0.14"
            stroke="var(--accent)"
            strokeWidth="1.2"
          />
          <text
            x="460"
            y="268"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--accent)"
          >
            MAT
          </text>
          <text
            x="460"
            y="286"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            堆 dump 深度分析
          </text>
          <text
            x="460"
            y="302"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            Dominator/Leak
          </text>
          <text
            x="460"
            y="318"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            内存泄漏权威
          </text>

          <rect
            x="550"
            y="248"
            width="150"
            height="80"
            rx="6"
            fill="var(--accent)"
            fillOpacity="0.18"
            stroke="var(--accent)"
            strokeWidth="1.2"
          />
          <text
            x="625"
            y="268"
            textAnchor="middle"
            fontSize="11"
            fontWeight="600"
            fill="var(--accent)"
          >
            Arthas
          </text>
          <text
            x="625"
            y="286"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            运行时热诊断
          </text>
          <text
            x="625"
            y="302"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            trace/watch/profiler
          </text>
          <text
            x="625"
            y="318"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            生产在线不停机
          </text>

          {/* 工具选择决策 */}
          <rect
            x="40"
            y="348"
            width="660"
            height="92"
            rx="8"
            fill="var(--text-primary)"
            fillOpacity="0.05"
            stroke="var(--text-primary)"
            strokeWidth="1"
            strokeOpacity="0.3"
          />
          <text
            x="370"
            y="370"
            textAnchor="middle"
            fontSize="12"
            fontWeight="600"
            fill="var(--text-primary)"
          >
            工具选择决策
          </text>
          <text
            x="370"
            y="390"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            快速看概览 &rarr; JConsole / VisualVM
          </text>
          <text
            x="370"
            y="408"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            内存泄漏深度分析 &rarr; MAT（dump 离线分析）
          </text>
          <text
            x="370"
            y="426"
            textAnchor="middle"
            fontSize="11"
            fill="var(--text-secondary)"
          >
            生产在线热诊断 &rarr; Arthas（thread/trace/profiler 不停机）
          </text>
        </svg>
      </div>
      <figcaption className="mt-2 text-center text-sm text-secondary">
        JVM 诊断工具——jps/jstat/jmap/jstack/jcmd 命令行、top+jstack CPU
        定位流程、JConsole/VisualVM/MAT/Arthas 可视化
      </figcaption>
    </figure>
  );
}
