import { OfficialJvt2Studio } from "./official-jvt2-lab";

const props = {
  "unitId": "jvt-2e-06-hidden-profiling",
  "unitTitle": "第6章 用剖析发现隐藏问题",
  "concepts": [
    "6 Finding hidden problems using profiling techniques",
    "6.1 Sampling to observe executing code",
    "6.2 Profiling to learn how many times a method is executed",
    "6.3 Using a profiler to identify SQL queries an app executes",
    "6.3.1 Using a profiler to retrieve SQL queries not generated by a framework",
    "6.3.2 Using the profiler to get the SQL queries generated by a framework",
    "6.3.3 Using the profiler to get programmatically generated SQL queries",
    "Summary"
  ],
  "stages": [
    "选择样本",
    "统计调用",
    "关联请求",
    "还原SQL",
    "验证优化"
  ],
  "focuses": [
    "sampling",
    "method count",
    "SQL text",
    "ORM",
    "动态SQL",
    "调用归因"
  ],
  "model": {
    "studio": "隐藏热点与SQL关联台",
    "axisA": {
      "label": "观测对象",
      "levels": [
        "CPU样本",
        "方法计数",
        "SQL事件"
      ]
    },
    "axisB": {
      "label": "关联粒度",
      "levels": [
        "进程总量",
        "线程请求",
        "trace到查询"
      ]
    },
    "outcomes": {
      "signal": "隐藏成本可见度",
      "risk": "热点错配率",
      "evidence": "证据闭环度"
    },
    "fault": "把高调用次数等同于高总成本，或只优化SQL文本却忽略调用放大",
    "task": "把一个高频方法和一条SQL关联到同一请求，分别计算单次与累计成本",
    "invariant": "热点结论同时包含频率、单次成本、累计成本与调用来源",
    "command": "jfr view hot-methods recording.jfr",
    "practiceMode": "calculation",
    "riskEffects": [
      1,
      -1
    ]
  }
} as const;

export function Jvt2e06HiddenProfilingInvestigationLab() {
  return <OfficialJvt2Studio {...props} mode="investigation" />;
}

export function Jvt2e06HiddenProfilingTimelineLab() {
  return <OfficialJvt2Studio {...props} mode="timeline" />;
}

export function Jvt2e06HiddenProfilingEvidenceLab() {
  return <OfficialJvt2Studio {...props} mode="evidence" />;
}
