"use client";
import { useMemo, useState } from "react";
type Mode = "regions" | "cycle" | "evidence";
type Props = { mode: Mode; unitTitle: string; focus: string; nodes: string[] };
const gates = ["源码版本", "对象与Region状态", "原始GC日志", "负面指标", "回滚与迁移"];
export function OfficialJg1BookLab({ mode, unitTitle, focus, nodes }: Props) {
  const [selected, setSelected] = useState(0); const [survival, setSurvival] = useState(35); const [failure, setFailure] = useState(false); const [checked, setChecked] = useState([true, false, false, false, false]);
  function resetExperiment() {
    setSelected(0);
    setSurvival(35);
    setFailure(false);
    setChecked([true, false, false, false, false]);
  }

  const visible = nodes.slice(0, 14); const score = useMemo(() => checked.filter(Boolean).length * 20, [checked]); const pause = Math.round(18 + survival * 1.55 + (failure ? 110 : 0)); const copied = Math.round(12 + survival * 0.72 + (failure ? 18 : 0));
  if (mode === "regions") return <section className="my-6 overflow-hidden rounded-md border border-zinc-300 bg-white text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "Region图"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><header className="border-b border-zinc-200 bg-emerald-50 px-4 py-3 dark:border-zinc-800 dark:bg-emerald-950/40"><p className="m-0 text-xs font-semibold uppercase text-emerald-800 dark:text-emerald-300">Region and source map</p><h3 className="m-0 mt-1 text-base font-bold">{unitTitle}</h3></header><div className="grid min-h-[290px] md:grid-cols-[minmax(0,1.2fr)_minmax(230px,0.8fr)]"><div className="grid content-start grid-cols-1 gap-2 border-b border-zinc-200 p-4 sm:grid-cols-2 md:border-b-0 md:border-r dark:border-zinc-800">{visible.map((node, index) => <button key={node} type="button" onClick={() => setSelected(index)} aria-pressed={selected === index} className={"min-h-12 rounded border px-3 py-2 text-left text-xs font-medium " + (selected === index ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-300 bg-zinc-50 text-zinc-800 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100")}><span className="mr-2 font-mono">{String(index + 1).padStart(2, "0")}</span>{node}</button>)}</div><div className="p-4"><p className="m-0 text-xs font-semibold text-rose-700 dark:text-rose-300">当前节点</p><p className="mt-2 min-h-12 text-sm font-bold">{visible[selected] ?? unitTitle}</p><p className="mt-3 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p><p className="mt-4 border-l-4 border-amber-500 pl-3 text-xs leading-5 text-zinc-600 dark:text-zinc-400">先画对象、Region、队列与线程，再进入源码函数。</p></div></div></section>;
  if (mode === "cycle") return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "周期实验"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><div className="flex flex-wrap items-start justify-between gap-3 border-b border-zinc-200 pb-3 dark:border-zinc-800"><div><p className="m-0 text-xs font-semibold text-cyan-700 dark:text-cyan-300">GC cycle experiment</p><h3 className="m-0 mt-1 text-base font-bold">存活率与疏散余量</h3></div><button type="button" onClick={() => setFailure((value) => !value)} aria-pressed={failure} className={"min-h-11 rounded border px-3 text-sm font-semibold " + (failure ? "border-rose-700 bg-rose-700 text-white" : "border-zinc-300 bg-zinc-50 text-zinc-800 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100")}>{failure ? "余量故障开启" : "注入余量故障"}</button></div><label htmlFor={unitTitle + "-survival"} className="mt-4 block text-sm font-medium">对象存活率：{survival}%</label><input id={unitTitle + "-survival"} type="range" min="5" max="95" value={survival} onChange={(event) => setSurvival(Number(event.target.value))} className="mt-2 w-full accent-cyan-700" /><div className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded border border-zinc-300 bg-zinc-300 dark:border-zinc-700 dark:bg-zinc-700"><div className="bg-white p-3 dark:bg-zinc-950"><p className="m-0 text-xs text-zinc-500">示意停顿</p><p className="m-0 mt-1 text-xl font-bold text-rose-700 dark:text-rose-300">{pause} ms</p></div><div className="bg-white p-3 dark:bg-zinc-950"><p className="m-0 text-xs text-zinc-500">示意复制</p><p className="m-0 mt-1 text-xl font-bold text-emerald-700 dark:text-emerald-300">{copied} regions</p></div></div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{focus}</p><p className="mt-2 text-xs leading-5 text-zinc-600 dark:text-zinc-400">示意值不代表真实G1测量；正式结论使用匹配JDK的原始日志与固定负载。</p></section>;
  return <section className="my-6 rounded-md border border-zinc-300 bg-white p-4 text-zinc-950 shadow-sm dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50" aria-label={unitTitle + "证据门"}>
      <span style={{position:'absolute',top:6,right:6,zIndex:20}}><button type="button" onClick={resetExperiment} title="重置实验" aria-label="重置实验" className="inline-flex size-11 shrink-0 items-center justify-center rounded border border-zinc-300 bg-white text-lg hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-950 dark:hover:bg-zinc-800"><span aria-hidden="true">↺</span></button></span><div className="flex items-center justify-between gap-3"><div><p className="m-0 text-xs font-semibold text-violet-700 dark:text-violet-300">Evidence gate</p><h3 className="m-0 mt-1 text-base font-bold">G1调优证据完整度</h3></div><output className="min-w-16 rounded border border-zinc-300 px-3 py-2 text-center text-lg font-bold dark:border-zinc-700">{score}%</output></div><div className="mt-4 divide-y divide-zinc-200 border-y border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800">{gates.map((gate, index) => <button key={gate} type="button" onClick={() => setChecked((current) => current.map((value, item) => item === index ? !value : value))} aria-pressed={checked[index]} className="flex min-h-11 w-full items-center justify-between gap-3 px-2 text-left text-sm hover:bg-zinc-50 dark:hover:bg-zinc-900"><span>{gate}</span><span className={"inline-flex h-6 w-6 items-center justify-center rounded border font-bold " + (checked[index] ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-400 text-transparent")}>✓</span></button>)}</div><p className="mt-4 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{score === 100 ? "证据齐全：由他人换一组负载重放并尝试推翻参数结论。" : "尚未闭环：缺失项必须绑定源码、对象状态、原始日志、负面指标或回滚实验。"}</p></section>;
}
